# DAND Project 3 - Wrangle and Analyze Data
### by Lakshmi Rajasekhar

## Data Used

This notebook is part of the work done towards Udacity's 'data wrangling' project in python for the Data Analyst Nanodegree. This details the wrangling steps performed for gathering, assessing and cleaning the 'WeRateDogs' twitter data for further analysis. For more details, please refer to the 'wrangling_report.pdf'.  
This project required the usage of three datasets:  
   1. **DATA 1 - WeRateDogs Twitter archive** - given by Udacity
   2. **DATA 2 - Tweet image predictions**, i.e., what breed of dog (or other object, animal, etc.) is present in each tweet according to a neural network - downloaded from udacity server using the given URL  
   3. **DATA 3 - Twitter API datadump** - data queried using twitter API using python tweepy library to collect data based on tweet_ids prresent in 'Data 1 - twitter archive' listed above. The scrapped data is further extracted for interesting variables for analysis.

## Library Imports

In [1]:
# All the imports required for this project
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import tweepy
import json

%matplotlib inline

## Gather

This step will gather all the data required (as listed in the 'Data used' section above) and import them as pandas dataframes.

### Importing Data 1 - twitter archive

In [2]:
# Read in the twitter archive for WeRateDogs
#weRateDogs_archive = pd.read_csv("twitter-archive-enhanced.csv", encoding = 'utf-8')
dogsTwitter_archive = pd.read_csv("twitter-archive-enhanced.csv")

# Examine the archive:
dogsTwitter_archive

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None
5,891087950875897856,NaN,NaN,2017-07-29 00:08:17 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a majestic great white breaching ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891087950...,13,10,None,None,None,None,None
6,890971913173991426,NaN,NaN,2017-07-28 16:27:12 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Meet Jax. He enjoys ice cream so much he gets ...,NaN,NaN,NaN,"https://gofundme.com/ydvmve-surgery-for-jax,ht...",13,10,Jax,None,None,None,None
7,890729181411237888,NaN,NaN,2017-07-28 00:22:40 +0000,"<a href=""http://twitter.com/download/iphone"" r...",When you watch your owner call another dog a g...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890729181...,13,10,None,None,None,None,None
8,890609185150312448,NaN,NaN,2017-07-27 16:25:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Zoey. She doesn't want to be one of th...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890609185...,13,10,Zoey,None,None,None,None
9,890240255349198849,NaN,NaN,2017-07-26 15:59:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Cassie. She is a college pup. Studying...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890240255...,14,10,Cassie,doggo,None,None,None
10,890006608113172480,NaN,NaN,2017-07-26 00:31:25 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Koda. He is a South Australian decksha...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890006608...,13,10,Koda,None,None,None,None
11,889880896479866881,NaN,NaN,2017-07-25 16:11:53 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Bruno. He is a service shark. Only get...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889880896...,13,10,Bruno,None,None,None,None
12,889665388333682689,NaN,NaN,2017-07-25 01:55:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here's a puppo that seems to be on the fence a...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889665388...,13,10,None,None,None,None,puppo
13,889638837579907072,NaN,NaN,2017-07-25 00:10:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Ted. He does his best. Sometimes that'...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889638837...,12,10,Ted,None,None,None,None
14,889531135344209921,NaN,NaN,2017-07-24 17:02:04 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Stuart. He's sporting his favorite fan...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889531135...,13,10,Stuart,None,None,None,puppo
15,889278841981685760,NaN,NaN,2017-07-24 00:19:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Oliver. You're witnessing one of his m...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889278841...,13,10,Oliver,None,None,None,None
16,888917238123831296,NaN,NaN,2017-07-23 00:22:39 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Jim. He found a fren. Taught him how t...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888917238...,12,10,Jim,None,None,None,None
17,888804989199671297,NaN,NaN,2017-07-22 16:56:37 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Zeke. He has a new stick. Very proud o...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888804989...,13,10,Zeke,None,None,None,None
18,888554962724278272,NaN,NaN,2017-07-22 00:23:06 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Ralphus. He's powering up. Attempting ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888554962...,13,10,Ralphus,None,None,None,None
19,888202515573088257,NaN,NaN,2017-07-21 01:02:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @dog_rates: This is Canela. She attempted s...,8.874740e+17,4.196984e+09,2017-07-19 00:47:34 +0000,https://twitter.com/dog_rates/status/887473957...,13,10,Canela,None,None,None,None
20,888078434458587136,NaN,NaN,2017-07-20 16:49:33 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Gerald. He was just told he didn't get...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888078434...,12,10,Gerald,None,None,None,None
21,887705289381826560,NaN,NaN,2017-07-19 16:06:48 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Jeffrey. He has a monopoly on the pool...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887705289...,13,10,Jeffrey,None,None,None,None
22,887517139158093824,NaN,NaN,2017-07-19 03:39:09 +0000,"<a href=""http://twitter.com/download/iphone"" r...",I've yet to rate a Venezuelan Hover Wiener. Th...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887517139...,14,10,such,None,None,None,None
23,887473957103951883,NaN,NaN,2017-07-19 00:47:34 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Canela. She attempted some fancy porch...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887473957...,13,10,Canela,None,None,None,None
24,887343217045368832,NaN,NaN,2017-07-18 16:08:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",You may not have known you needed to see this ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887343217...,13,10,None,None,None,None,None
25,887101392804085760,NaN,NaN,2017-07-18 00:07:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This... is a Jubilant Antarctic House Bear. We...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887101392...,12,10,None,None,None,None,None
26,886983233522544640,NaN,NaN,2017-07-17 16:17:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Maya. She's very shy. Rarely leaves he...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886983233...,13,10,Maya,None,None,None,None
27,886736880519319552,NaN,NaN,2017-07-16 23:58:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Mingus. He's a wonderful father to his...,NaN,NaN,NaN,"https://www.gofundme.com/mingusneedsus,https:/...",13,10,Mingus,None,None,None,None
28,886680336477933568,NaN,NaN,2017-07-16 20:14:00 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Derek. He's late for a dog meeting. 13...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886680336...,13,10,Derek,None,None,None,None
29,886366144734445568,NaN,NaN,2017-07-15 23:25:31 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Roscoe. Another pupper fallen victim t...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886366144...,12,10,Roscoe,None,None,pupper,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326,666411507551481857,NaN,NaN,2015-11-17 00:24:19 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is quite the dog. Gets really excited whe...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666411507...,2,10,quite,None,None,None,None
2327,666407126856765440,NaN,NaN,2015-11-17 00:06:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a southern Vesuvius bumblegruff. Can d...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666407126...,7,10,a,None,None,None,None
2328,666396247373291520,NaN,NaN,2015-11-16 23:23:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Oh goodness. A super rare northeast Qdoba kang...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666396247...,9,10,None,None,None,None,None
2329,666373753744588802,NaN,NaN,2015-11-16 21:54:18 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Those are sunglasses and a jean jacket. 11/10 ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666373753...,11,10,None,None,None,None,None
2330,666362758909284353,NaN,NaN,2015-11-16 21:10:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Unique dog here. Very small. Lives in containe...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666362758...,6,10,None,None,None,None,None
2331,666353288456101888,NaN,NaN,2015-11-16 20:32:58 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a mixed Asiago from the Galápagos...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666353288...,8,10,None,None,None,None,None
2332,666345417576210432,NaN,NaN,2015-11-16 20:01:42 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Look at this jokester thinking seat belt laws ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666345417...,10,10,None,None,None,None,None
2333,666337882303524864,NaN,NaN,2015-11-16 19:31:45 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an extremely rare horned Parthenon. No...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666337882...,9,10,an,None,None,None,None
2334,666293911632134144,NaN,NaN,2015-11-16 16:37:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a funny dog. Weird toes. Won't come do...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666293911...,3,10,a,None,None,None,None
2335,666287406224695296,NaN,NaN,2015-11-16 16:11:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an Albanian 3 1/2 legged Episcopalian...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666287406...,1,2,an,None,None,None,None
2336,666273097616637952,NaN,NaN,2015-11-16 15:14:19 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Can take selfies 11/10 https://t.co/ws2AMaNwPW,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666273097...,11,10,None,None,None,None,None
2337,666268910803644416,NaN,NaN,2015-11-16 14:57:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Very concerned about fellow dog trapped in com...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666268910...,10,10,None,None,None,None,None
2338,666104133288665088,NaN,NaN,2015-11-16 04:02:55 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Not familiar with this breed. No tail (weird)....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666104133...,1,10,None,None,None,None,None
2339,666102155909144576,NaN,NaN,2015-11-16 03:55:04 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Oh my. Here you are seeing an Adobe Setter giv...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666102155...,11,10,None,None,None,None,None
2340,666099513787052032,NaN,NaN,2015-11-16 03:44:34 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Can stand on stump for what seems like a while...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666099513...,8,10,None,None,None,None,None
2341,666094000022159362,NaN,NaN,2015-11-16 03:22:39 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This appears to be a Mongolian Presbyterian mi...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666094000...,9,10,None,None,None,None,None
2342,666082916733198337,NaN,NaN,2015-11-16 02:38:37 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a well-established sunblockerspan...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666082916...,6,10,None,None,None,None,None
2343,666073100786774016,NaN,NaN,2015-11-16 01:59:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Let's hope this flight isn't Malaysian (lol). ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666073100...,10,10,None,None,None,None,None
2344,666071193221509120,NaN,NaN,2015-11-16 01:52:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a northern speckled Rhododendron....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666071193...,9,10,None,None,None,None,None
2345,666063827256086533,NaN,NaN,2015-11-16 01:22:45 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is the happiest dog you will ever see. Ve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666063827...,10,10,the,None,None,None,None
2346,666058600524156928,NaN,NaN,2015-11-16 01:01:59 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is the Rand Paul of retrievers folks! He'...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666058600...,8,10,the,None,None,None,None
2347,666057090499244032,NaN,NaN,2015-11-16 00:55:59 +0000,"<a href=""http://twitter.com/download/iphone"" r...",My oh my. This is a rare blond Canadian terrie...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666057090...,9,10,a,None,None,None,None
2348,666055525042405380,NaN,NaN,2015-11-16 00:49:46 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a Siberian heavily armored polar bear ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666055525...,10,10,a,None,None,None,None
2349,666051853826850816,NaN,NaN,2015-11-16 00:35:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an odd dog. Hard on the outside but lo...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666051853...,2,10,an,None,None,None,None
2350,666050758794694657,NaN,NaN,2015-11-16 00:30:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a truly beautiful English Wilson Staff...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666050758...,10,10,a,None,None,None,None
2351,666049248165822465,NaN,NaN,2015-11-16 00:24:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a 1949 1st generation vulpix. Enj...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666049248...,5,10,None,None,None,None,None
2352,666044226329800704,NaN,NaN,2015-11-16 00:04:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a purebred Piers Morgan. Loves to Netf...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666044226...,6,10,a,None,None,None,None
2353,666033412701032449,NaN,NaN,2015-11-15 23:21:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a very happy pup. Big fan of well-main...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666033412...,9,10,a,None,None,None,None
2354,666029285002620928,NaN,NaN,2015-11-15 23:05:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a western brown Mitsubishi terrier. Up...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666029285...,7,10,a,None,None,None,None
2355,666020888022790149,NaN,NaN,2015-11-15 22:32:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a Japanese Irish Setter. Lost eye...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666020888...,8,10,None,None,None,None,None

### Gathering and Importing Data 2 - image prediction files

In [3]:
#Extract the image prediction file from the url provided
URL = 'https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv'
response = requests.get(URL)
response

with open(URL.split('/')[-1], mode = 'wb') as file:
    file.write(response.content)
    
# Read the downloaded images file using pandas dataframe
dog_images = pd.read_csv("image-predictions.tsv", sep = '\t', encoding = 'utf-8')
dog_images

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True
5,666050758794694657,https://pbs.twimg.com/media/CT5Jof1WUAEuVxN.jpg,1,Bernese_mountain_dog,0.651137,True,English_springer,0.263788,True,Greater_Swiss_Mountain_dog,0.016199,True
6,666051853826850816,https://pbs.twimg.com/media/CT5KoJ1WoAAJash.jpg,1,box_turtle,0.933012,False,mud_turtle,0.045885,False,terrapin,0.017885,False
7,666055525042405380,https://pbs.twimg.com/media/CT5N9tpXIAAifs1.jpg,1,chow,0.692517,True,Tibetan_mastiff,0.058279,True,fur_coat,0.054449,False
8,666057090499244032,https://pbs.twimg.com/media/CT5PY90WoAAQGLo.jpg,1,shopping_cart,0.962465,False,shopping_basket,0.014594,False,golden_retriever,0.007959,True
9,666058600524156928,https://pbs.twimg.com/media/CT5Qw94XAAA_2dP.jpg,1,miniature_poodle,0.201493,True,komondor,0.192305,True,soft-coated_wheaten_terrier,0.082086,True
10,666063827256086533,https://pbs.twimg.com/media/CT5Vg_wXIAAXfnj.jpg,1,golden_retriever,0.775930,True,Tibetan_mastiff,0.093718,True,Labrador_retriever,0.072427,True
11,666071193221509120,https://pbs.twimg.com/media/CT5cN_3WEAAlOoZ.jpg,1,Gordon_setter,0.503672,True,Yorkshire_terrier,0.174201,True,Pekinese,0.109454,True
12,666073100786774016,https://pbs.twimg.com/media/CT5d9DZXAAALcwe.jpg,1,Walker_hound,0.260857,True,English_foxhound,0.175382,True,Ibizan_hound,0.097471,True
13,666082916733198337,https://pbs.twimg.com/media/CT5m4VGWEAAtKc8.jpg,1,pug,0.489814,True,bull_mastiff,0.404722,True,French_bulldog,0.048960,True
14,666094000022159362,https://pbs.twimg.com/media/CT5w9gUW4AAsBNN.jpg,1,bloodhound,0.195217,True,German_shepherd,0.078260,True,malinois,0.075628,True
15,666099513787052032,https://pbs.twimg.com/media/CT51-JJUEAA6hV8.jpg,1,Lhasa,0.582330,True,Shih-Tzu,0.166192,True,Dandie_Dinmont,0.089688,True
16,666102155909144576,https://pbs.twimg.com/media/CT54YGiWUAEZnoK.jpg,1,English_setter,0.298617,True,Newfoundland,0.149842,True,borzoi,0.133649,True
17,666104133288665088,https://pbs.twimg.com/media/CT56LSZWoAAlJj2.jpg,1,hen,0.965932,False,cock,0.033919,False,partridge,0.000052,False
18,666268910803644416,https://pbs.twimg.com/media/CT8QCd1WEAADXws.jpg,1,desktop_computer,0.086502,False,desk,0.085547,False,bookcase,0.079480,False
19,666273097616637952,https://pbs.twimg.com/media/CT8T1mtUwAA3aqm.jpg,1,Italian_greyhound,0.176053,True,toy_terrier,0.111884,True,basenji,0.111152,True
20,666287406224695296,https://pbs.twimg.com/media/CT8g3BpUEAAuFjg.jpg,1,Maltese_dog,0.857531,True,toy_poodle,0.063064,True,miniature_poodle,0.025581,True
21,666293911632134144,https://pbs.twimg.com/media/CT8mx7KW4AEQu8N.jpg,1,three-toed_sloth,0.914671,False,otter,0.015250,False,great_grey_owl,0.013207,False
22,666337882303524864,https://pbs.twimg.com/media/CT9OwFIWEAMuRje.jpg,1,ox,0.416669,False,Newfoundland,0.278407,True,groenendael,0.102643,True
23,666345417576210432,https://pbs.twimg.com/media/CT9Vn7PWoAA_ZCM.jpg,1,golden_retriever,0.858744,True,Chesapeake_Bay_retriever,0.054787,True,Labrador_retriever,0.014241,True
24,666353288456101888,https://pbs.twimg.com/media/CT9cx0tUEAAhNN_.jpg,1,malamute,0.336874,True,Siberian_husky,0.147655,True,Eskimo_dog,0.093412,True
25,666362758909284353,https://pbs.twimg.com/media/CT9lXGsUcAAyUFt.jpg,1,guinea_pig,0.996496,False,skunk,0.002402,False,hamster,0.000461,False
26,666373753744588802,https://pbs.twimg.com/media/CT9vZEYWUAAlZ05.jpg,1,soft-coated_wheaten_terrier,0.326467,True,Afghan_hound,0.259551,True,briard,0.206803,True
27,666396247373291520,https://pbs.twimg.com/media/CT-D2ZHWIAA3gK1.jpg,1,Chihuahua,0.978108,True,toy_terrier,0.009397,True,papillon,0.004577,True
28,666407126856765440,https://pbs.twimg.com/media/CT-NvwmW4AAugGZ.jpg,1,black-and-tan_coonhound,0.529139,True,bloodhound,0.244220,True,flat-coated_retriever,0.173810,True
29,666411507551481857,https://pbs.twimg.com/media/CT-RugiWIAELEaq.jpg,1,coho,0.404640,False,barracouta,0.271485,False,gar,0.189945,False
...,...,...,...,...,...,...,...,...,...,...,...,...
2045,886366144734445568,https://pbs.twimg.com/media/DE0BTnQUwAApKEH.jpg,1,French_bulldog,0.999201,True,Chihuahua,0.000361,True,Boston_bull,0.000076,True
2046,886680336477933568,https://pbs.twimg.com/media/DE4fEDzWAAAyHMM.jpg,1,convertible,0.738995,False,sports_car,0.139952,False,car_wheel,0.044173,False
2047,886736880519319552,https://pbs.twimg.com/media/DE5Se8FXcAAJFx4.jpg,1,kuvasz,0.309706,True,Great_Pyrenees,0.186136,True,Dandie_Dinmont,0.086346,True
2048,886983233522544640,https://pbs.twimg.com/media/DE8yicJW0AAAvBJ.jpg,2,Chihuahua,0.793469,True,toy_terrier,0.143528,True,can_opener,0.032253,False
2049,887101392804085760,https://pbs.twimg.com/media/DE-eAq6UwAA-jaE.jpg,1,Samoyed,0.733942,True,Eskimo_dog,0.035029,True,Staffordshire_bullterrier,0.029705,True
2050,887343217045368832,https://pbs.twimg.com/ext_tw_video_thumb/88734...,1,Mexican_hairless,0.330741,True,sea_lion,0.275645,False,Weimaraner,0.134203,True
2051,887473957103951883,https://pbs.twimg.com/media/DFDw2tyUQAAAFke.jpg,2,Pembroke,0.809197,True,Rhodesian_ridgeback,0.054950,True,beagle,0.038915,True
2052,887517139158093824,https://pbs.twimg.com/ext_tw_video_thumb/88751...,1,limousine,0.130432,False,tow_truck,0.029175,False,shopping_cart,0.026321,False
2053,887705289381826560,https://pbs.twimg.com/media/DFHDQBbXgAEqY7t.jpg,1,basset,0.821664,True,redbone,0.087582,True,Weimaraner,0.026236,True
2054,888078434458587136,https://pbs.twimg.com/media/DFMWn56WsAAkA7B.jpg,1,French_bulldog,0.995026,True,pug,0.000932,True,bull_mastiff,0.000903,True
2055,888202515573088257,https://pbs.twimg.com/media/DFDw2tyUQAAAFke.jpg,2,Pembroke,0.809197,True,Rhodesian_ridgeback,0.054950,True,beagle,0.038915,True
2056,888554962724278272,https://pbs.twimg.com/media/DFTH_O-UQAACu20.jpg,3,Siberian_husky,0.700377,True,Eskimo_dog,0.166511,True,malamute,0.111411,True
2057,888804989199671297,https://pbs.twimg.com/media/DFWra-3VYAA2piG.jpg,1,golden_retriever,0.469760,True,Labrador_retriever,0.184172,True,English_setter,0.073482,True
2058,888917238123831296,https://pbs.twimg.com/media/DFYRgsOUQAARGhO.jpg,1,golden_retriever,0.714719,True,Tibetan_mastiff,0.120184,True,Labrador_retriever,0.105506,True
2059,889278841981685760,https://pbs.twimg.com/ext_tw_video_thumb/88927...,1,whippet,0.626152,True,borzoi,0.194742,True,Saluki,0.027351,True
2060,889531135344209921,https://pbs.twimg.com/media/DFg_2PVW0AEHN3p.jpg,1,golden_retriever,0.953442,True,Labrador_retriever,0.013834,True,redbone,0.007958,True
2061,889638837579907072,https://pbs.twimg.com/media/DFihzFfXsAYGDPR.jpg,1,French_bulldog,0.991650,True,boxer,0.002129,True,Staffordshire_bullterrier,0.001498,True
2062,889665388333682689,https://pbs.twimg.com/media/DFi579UWsAAatzw.jpg,1,Pembroke,0.966327,True,Cardigan,0.027356,True,basenji,0.004633,True
2063,889880896479866881,https://pbs.twimg.com/media/DFl99B1WsAITKsg.jpg,1,French_bulldog,0.377417,True,Labrador_retriever,0.151317,True,muzzle,0.082981,False
2064,890006608113172480,https://pbs.twimg.com/media/DFnwSY4WAAAMliS.jpg,1,Samoyed,0.957979,True,Pomeranian,0.013884,True,chow,0.008167,True
2065,890240255349198849,https://pbs.twimg.com/media/DFrEyVuW0AAO3t9.jpg,1,Pembroke,0.511319,True,Cardigan,0.451038,True,Chihuahua,0.029248,True
2066,890609185150312448,https://pbs.twimg.com/media/DFwUU__XcAEpyXI.jpg,1,Irish_terrier,0.487574,True,Irish_setter,0.193054,True,Chesapeake_Bay_retriever,0.118184,True
2067,890729181411237888,https://pbs.twimg.com/media/DFyBahAVwAAhUTd.jpg,2,Pomeranian,0.566142,True,Eskimo_dog,0.178406,True,Pembroke,0.076507,True
2068,890971913173991426,https://pbs.twimg.com/media/DF1eOmZXUAALUcq.jpg,1,Appenzeller,0.341703,True,Border_collie,0.199287,True,ice_lolly,0.193548,False
2069,891087950875897856,https://pbs.twimg.com/media/DF3HwyEWsAABqE6.jpg,1,Chesapeake_Bay_retriever,0.425595,True,Irish_terrier,0.116317,True,Indian_elephant,0.076902,False
2070,891327558926688256,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,2,basset,0.555712,True,English_springer,0.225770,True,German_short-haired_pointer,0.175219,True
2071,891689557279858688,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,1,paper_towel,0.170278,False,Labrador_retriever,0.168086,True,spatula,0.040836,False
2072,891815181378084864,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,1,Chihuahua,0.716012,True,malamute,0.078253,True,kelpie,0.031379,True
2073,892177421306343426,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,1,Chihuahua,0.323581,True,Pekinese,0.090647,True,papillon,0.068957,True
2074,892420643555336193,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,1,orange,0.097049,False,bagel,0.085851,False,banana,0.076110,False

### Gathering and Importing Data 3 - twitter API datadump

**NOTE:** The below chunks of code for extracting data using twitter API and tweepy are converted into raw code blocks so that the notebook runs without running those cells again. If required, these cells can be converted back into code cells for execution.

## Twitter API data scrapping - not to be run always

# For gathering the number of re-tweets and likes for each WeRateDogs tweets, 
# Step 1- We first create authenticate and register our ap in https://apps.twitter.com
# Step 2 - Then we generate the required consumer (API) key and secret, access token and secret.

# The actual keys and secrets are replaced by placeholders below for privacy reasons
consumer_key = 'place holder'
consumer_secret = 'place holder'
access_token = 'place holder'
access_token_secret = 'place holder'

## Twitter API data scrapping - not to be run always

# Although imports section at the beginning has all the library imports, I prefer to have it in-between 
# codes where the import happens and then comment it out after copy-pasting the imports command to the 
# imports section above at the end of coding the whole file. This gives me a flow while coding

#import tweepy

# Reading the tweepy documentation, we need to first create an authorization handler and then get access to it
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

# Creating an api object with parsing the results into a JSON object
api = tweepy.API(auth, parser = tweepy.parsers.JSONParser(), wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

api

## Twitter API data scrapping - not to be run always

# For each tweet_id in the given archive, download the data and append it into a list
tweets_dataDump = []
tweetids_with_errors = []

# making a temp copy json file for safety purposes while scrapping web
with open('tweet_json_temp.txt', 'a', encoding='utf8') as f:
    for tweet_id in dogsTwitter_archive['tweet_id']:
        try:
            tweet = api.get_status(tweet_id, tweet_mode = 'extended')
            tweets_dataDump.append(tweet)
            json.dump(tweet, f)
            f.write('\n')
        except Exception as e:
            print("tweet_id:", str(tweet_id), "Error is - " + str(e))
            tweetids_with_errors.append(tweet_id)
            
#Future work: Manually see the tweet_id with errors 'tweetids_with_errors' and then add them manually to the dataframe if possible

## Twitter API data scrapping - not to be run always

# Write the tweets dump into the 'tweet_json.txt' file
with open('tweet_json.txt', 'w') as file:
        file.write(json.dumps(tweets_dataDump, indent=2))

In [4]:
# For loop to append each tweet into a list
twitter_extractedData = []

with open('tweet_json.txt', encoding='utf8') as tweets_dataDump:
    twitter_dataDump = json.load(tweets_dataDump)
    # From each tweet data, extract interested data
    for tweet in twitter_dataDump:
        try:
            tweet_id = tweet['id']
            retweet_count = tweet['retweet_count']
            likes = tweet['favorite_count']
            full_text = tweet["full_text"]

            #append the variables of interest to a list to be read in as a pandas dataframe later on
            twitter_extractedData.append({"tweet_id": tweet_id, 
                                        "retweet_count": retweet_count,
                                        "likes": likes,
                                        "full_text": full_text})
        except Exception as e:
            print("Error is - " + str(e))

In [5]:
twitter_extractedDF = pd.DataFrame(twitter_extractedData)
# Rearranging columns
#cols = list(twitter_extractedDF.columns.values)
#cols
twitter_extractedDF = twitter_extractedDF[['tweet_id','retweet_count','likes','full_text']]
twitter_extractedDF

,tweet_id,retweet_count,likes,full_text
0,892420643555336193,8738,39196,This is Phineas. He's a mystical boy. Only eve...
1,892177421306343426,6411,33567,This is Tilly. She's just checking pup on you....
2,891815181378084864,4257,25304,This is Archie. He is a rare Norwegian Pouncin...
3,891689557279858688,8834,42553,This is Darla. She commenced a snooze mid meal...
4,891327558926688256,9617,40741,This is Franklin. He would like you to stop ca...
5,891087950875897856,3199,20421,Here we have a majestic great white breaching ...
6,890971913173991426,2123,11972,Meet Jax. He enjoys ice cream so much he gets ...
7,890729181411237888,19350,66245,When you watch your owner call another dog a g...
8,890609185150312448,4357,28032,This is Zoey. She doesn't want to be one of th...
9,890240255349198849,7589,32270,This is Cassie. She is a college pup. Studying...
10,890006608113172480,7501,30929,This is Koda. He is a South Australian decksha...
11,889880896479866881,5072,28048,This is Bruno. He is a service shark. Only get...
12,889665388333682689,10272,48307,Here's a puppo that seems to be on the fence a...
13,889638837579907072,4653,27456,This is Ted. He does his best. Sometimes that'...
14,889531135344209921,2282,15243,This is Stuart. He's sporting his favorite fan...
15,889278841981685760,5563,25552,This is Oliver. You're witnessing one of his m...
16,888917238123831296,4625,29369,This is Jim. He found a fren. Taught him how t...
17,888804989199671297,4473,25859,This is Zeke. He has a new stick. Very proud o...
18,888554962724278272,3677,20135,This is Ralphus. He's powering up. Attempting ...
19,888078434458587136,3601,22005,This is Gerald. He was just told he didn't get...
20,887705289381826560,5530,30502,This is Jeffrey. He has a monopoly on the pool...
21,887517139158093824,11922,46662,I've yet to rate a Venezuelan Hover Wiener. Th...
22,887473957103951883,18679,69860,This is Canela. She attempted some fancy porch...
23,887343217045368832,10617,33997,You may not have known you needed to see this ...
24,887101392804085760,6094,30862,This... is a Jubilant Antarctic House Bear. We...
25,886983233522544640,7945,35542,This is Maya. She's very shy. Rarely leaves he...
26,886736880519319552,3372,12199,This is Mingus. He's a wonderful father to his...
27,886680336477933568,4562,22646,This is Derek. He's late for a dog meeting. 13...
28,886366144734445568,3255,21352,This is Roscoe. Another pupper fallen victim t...
29,886267009285017600,4,117,@NonWhiteHat @MayhewMayhem omg hello tanner yo...
...,...,...,...,...
2317,666411507551481857,336,454,This is quite the dog. Gets really excited whe...
2318,666407126856765440,42,112,This is a southern Vesuvius bumblegruff. Can d...
2319,666396247373291520,90,170,Oh goodness. A super rare northeast Qdoba kang...
2320,666373753744588802,95,193,Those are sunglasses and a jean jacket. 11/10 ...
2321,666362758909284353,584,791,Unique dog here. Very small. Lives in containe...
2322,666353288456101888,74,227,Here we have a mixed Asiago from the Galápagos...
2323,666345417576210432,144,305,Look at this jokester thinking seat belt laws ...
2324,666337882303524864,95,202,This is an extremely rare horned Parthenon. No...
2325,666293911632134144,364,514,This is a funny dog. Weird toes. Won't come do...
2326,666287406224695296,69,151,This is an Albanian 3 1/2 legged Episcopalian...
2327,666273097616637952,79,179,Can take selfies 11/10 https://t.co/ws2AMaNwPW
2328,666268910803644416,36,106,Very concerned about fellow dog trapped in com...
2329,666104133288665088,6768,14581,Not familiar with this breed. No tail (weird)....
2330,666102155909144576,14,80,Oh my. Here you are seeing an Adobe Setter giv...
2331,666099513787052032,72,159,Can stand on stump for what seems like a while...
2332,666094000022159362,76,166,This appears to be a Mongolian Presbyterian mi...
2333,666082916733198337,46,120,Here we have a well-established sunblockerspan...
2334,666073100786774016,172,328,Let's hope this flight isn't Malaysian (lol). ...
2335,666071193221509120,65,153,Here we have a northern speckled Rhododendron....
2336,666063827256086533,226,488,This is the happiest dog you will ever see. Ve...
2337,666058600524156928,59,115,Here is the Rand Paul of retrievers folks! He'...
2338,666057090499244032,144,303,My oh my. This is a rare blond Canadian terrie...
2339,666055525042405380,259,446,Here is a Siberian heavily armored polar bear ...
2340,666051853826850816,868,1241,This is an odd dog. Hard on the outside but lo...
2341,666050758794694657,59,135,This is a truly beautiful English Wilson Staff...
2342,666049248165822465,40,110,Here we have a 1949 1st generation vulpix. Enj...
2343,666044226329800704,143,305,This is a purebred Piers Morgan. Loves to Netf...
2344,666033412701032449,46,126,Here is a very happy pup. Big fan of well-main...
2345,666029285002620928,47,131,This is a western brown Mitsubishi terrier. Up...
2346,666020888022790149,523,2530,Here we have a Japanese Irish Setter. Lost eye...

In [6]:
#Check the structure of the dataframe
twitter_extractedDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2347 entries, 0 to 2346
Data columns (total 4 columns):
tweet_id         2347 non-null int64
retweet_count    2347 non-null int64
likes            2347 non-null int64
full_text        2347 non-null object
dtypes: int64(3), object(1)
memory usage: 73.4+ KB

## Access

After gathering the data, this section would consist of assessing any quality and tidiness issues in the three datasets gathered. The assessment would be done both visually and programmatically.  

All the issues noted are listed at the end of this section.

### Assessment for data1 - twitter archive

In [7]:
# structure of the dataframe
dogsTwitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

In [8]:
# look at the first few records in the data frame for visual inspection
dogsTwitter_archive.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None

In [9]:
# look at he last few records
dogsTwitter_archive.tail()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
2351,666049248165822465,NaN,NaN,2015-11-16 00:24:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a 1949 1st generation vulpix. Enj...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666049248...,5,10,None,None,None,None,None
2352,666044226329800704,NaN,NaN,2015-11-16 00:04:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a purebred Piers Morgan. Loves to Netf...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666044226...,6,10,a,None,None,None,None
2353,666033412701032449,NaN,NaN,2015-11-15 23:21:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a very happy pup. Big fan of well-main...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666033412...,9,10,a,None,None,None,None
2354,666029285002620928,NaN,NaN,2015-11-15 23:05:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a western brown Mitsubishi terrier. Up...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666029285...,7,10,a,None,None,None,None
2355,666020888022790149,NaN,NaN,2015-11-15 22:32:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a Japanese Irish Setter. Lost eye...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666020888...,8,10,None,None,None,None,None

In [10]:
# summary of the dataframe
#dogsTwitter_archive.describe(include = 'all')
dogsTwitter_archive.describe()
#NOTE: the min and max values of rating numerator and denominator seems to be unusual. possibilty of data issues for this columns

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,retweeted_status_id,retweeted_status_user_id,rating_numerator,rating_denominator
count,2.356000e+03,7.800000e+01,7.800000e+01,1.810000e+02,1.810000e+02,2356.000000,2356.000000
mean,7.427716e+17,7.455079e+17,2.014171e+16,7.720400e+17,1.241698e+16,13.126486,10.455433
std,6.856705e+16,7.582492e+16,1.252797e+17,6.236928e+16,9.599254e+16,45.876648,6.745237
min,6.660209e+17,6.658147e+17,1.185634e+07,6.661041e+17,7.832140e+05,0.000000,0.000000
25%,6.783989e+17,6.757419e+17,3.086374e+08,7.186315e+17,4.196984e+09,10.000000,10.000000
50%,7.196279e+17,7.038708e+17,4.196984e+09,7.804657e+17,4.196984e+09,11.000000,10.000000
75%,7.993373e+17,8.257804e+17,4.196984e+09,8.203146e+17,4.196984e+09,12.000000,10.000000
max,8.924206e+17,8.862664e+17,8.405479e+17,8.874740e+17,7.874618e+17,1776.000000,170.000000

In [11]:
# look at the column names
dogsTwitter_archive.columns.values

array(['tweet_id', 'in_reply_to_status_id', 'in_reply_to_user_id',
       'timestamp', 'source', 'text', 'retweeted_status_id',
       'retweeted_status_user_id', 'retweeted_status_timestamp',
       'expanded_urls', 'rating_numerator', 'rating_denominator', 'name',
       'doggo', 'floofer', 'pupper', 'puppo'], dtype=object)

In [12]:
# Unique values in a column in the dataframe
print(pd.unique(dogsTwitter_archive[['name']].values.ravel()))  # possible errors in names (some are 'an', 'mad' etc)
print("----------------------------------------------------------------")
print(pd.unique(dogsTwitter_archive[['text']].values.ravel()))  # URLs with text. have to clean this up
print("----------------------------------------------------------------")
print(pd.unique(dogsTwitter_archive[['source']].values.ravel()))# has html embeddings to be removed

['Phineas' 'Tilly' 'Archie' 'Darla' 'Franklin' 'None' 'Jax' 'Zoey' 'Cassie'
 'Koda' 'Bruno' 'Ted' 'Stuart' 'Oliver' 'Jim' 'Zeke' 'Ralphus' 'Canela'
 'Gerald' 'Jeffrey' 'such' 'Maya' 'Mingus' 'Derek' 'Roscoe' 'Waffles'
 'Jimbo' 'Maisey' 'Lilly' 'Earl' 'Lola' 'Kevin' 'Yogi' 'Noah' 'Bella'
 'Grizzwald' 'Rusty' 'Gus' 'Stanley' 'Alfy' 'Koko' 'Rey' 'Gary' 'a'
 'Elliot' 'Louis' 'Jesse' 'Romeo' 'Bailey' 'Duddles' 'Jack' 'Emmy' 'Steven'
 'Beau' 'Snoopy' 'Shadow' 'Terrance' 'Aja' 'Penny' 'Dante' 'Nelly' 'Ginger'
 'Benedict' 'Venti' 'Goose' 'Nugget' 'Cash' 'Coco' 'Jed' 'Sebastian'
 'Walter' 'Sierra' 'Monkey' 'Harry' 'Kody' 'Lassie' 'Rover' 'Napolean'
 'Dawn' 'Boomer' 'Cody' 'Rumble' 'Clifford' 'quite' 'Dewey' 'Scout' 'Gizmo'
 'Cooper' 'Harold' 'Shikha' 'Jamesy' 'Lili' 'Sammy' 'Meatball' 'Paisley'
 'Albus' 'Neptune' 'Quinn' 'Belle' 'Zooey' 'Dave' 'Jersey' 'Hobbes' 'Burt'
 'Lorenzo' 'Carl' 'Jordy' 'Milky' 'Trooper' 'Winston' 'Sophie' 'Wyatt'
 'Rosie' 'Thor' 'Oscar' 'Luna' 'Callie' 'Cermet' 'George' 'Marlee' 'Arya'
 'Einstein' 'Alice' 'Rumpole' 'Benny' 'Aspen' 'Jarod' 'Wiggles' 'General'
 'Sailor' 'Astrid' 'Iggy' 'Snoop' 'Kyle' 'Leo' 'Riley' 'Gidget' 'Noosh'
 'Odin' 'Jerry' 'Charlie' 'Georgie' 'Rontu' 'Cannon' 'Furzey' 'Daisy'
 'Tuck' 'Barney' 'Vixen' 'Jarvis' 'Mimosa' 'Pickles' 'Bungalo' 'Brady'
 'Margo' 'Sadie' 'Hank' 'Tycho' 'Stephan' 'Indie' 'Winnie' 'Bentley' 'Ken'
 'Max' 'Maddie' 'Pipsy' 'Monty' 'Sojourner' 'Odie' 'Arlo' 'Sunny' 'Vincent'
 'Lucy' 'Clark' 'Mookie' 'Meera' 'Buddy' 'Ava' 'Rory' 'Eli' 'Ash' 'Tucker'
 'Tobi' 'Chester' 'Wilson' 'Sunshine' 'Lipton' 'Gabby' 'Bronte' 'Poppy'
 'Rhino' 'Willow' 'not' 'Orion' 'Eevee' 'Smiley' 'Logan' 'Moreton' 'Klein'
 'Miguel' 'Emanuel' 'Kuyu' 'Dutch' 'Pete' 'Scooter' 'Reggie' 'Kyro'
 'Samson' 'Loki' 'Mia' 'Malcolm' 'Dexter' 'Alfie' 'Fiona' 'one' 'Mutt'
 'Bear' 'Doobert' 'Beebop' 'Alexander' 'Sailer' 'Brutus' 'Kona' 'Boots'
 'Ralphie' 'Phil' 'Cupid' 'Pawnd' 'Pilot' 'Ike' 'Mo' 'Toby' 'Sweet' 'Pablo'
 'Nala' 'Balto' 'Crawford' 'Gabe' 'Mattie' 'Jimison' 'Hercules' 'Duchess'
 'Harlso' 'Sampson' 'Sundance' 'Luca' 'Flash' 'Finn' 'Peaches' 'Howie'
 'Jazzy' 'Anna' 'Bo' 'Seamus' 'Wafer' 'Chelsea' 'Tom' 'Moose' 'Florence'
 'Autumn' 'Dido' 'Eugene' 'Herschel' 'Strudel' 'Tebow' 'Chloe' 'Betty'
 'Timber' 'Binky' 'Dudley' 'Comet' 'Larry' 'Levi' 'Akumi' 'Titan' 'Olivia'
 'Alf' 'Oshie' 'Bruce' 'Chubbs' 'Sky' 'Atlas' 'Eleanor' 'Layla' 'Rocky'
 'Baron' 'Tyr' 'Bauer' 'Swagger' 'Brandi' 'Mary' 'Moe' 'Halo' 'Augie'
 'Craig' 'Sam' 'Hunter' 'Pavlov' 'Maximus' 'Wallace' 'Ito' 'Milo' 'Ollie'
 'Cali' 'Lennon' 'incredibly' 'Major' 'Duke' 'Reginald' 'Sansa' 'Shooter'
 'Django' 'Diogi' 'Sonny' 'Philbert' 'Marley' 'Severus' 'Ronnie' 'Anakin'
 'Bones' 'Mauve' 'Chef' 'Doc' 'Sobe' 'Longfellow' 'Mister' 'Iroh' 'Baloo'
 'Stubert' 'Paull' 'Timison' 'Davey' 'Pancake' 'Tyrone' 'Snicku' 'Ruby'
 'Brody' 'Rizzy' 'Mack' 'Butter' 'Nimbus' 'Laika' 'Dobby' 'Juno' 'Maude'
 'Lily' 'Newt' 'Benji' 'Nida' 'Robin' 'Monster' 'BeBe' 'Remus' 'Mabel'
 'Misty' 'Happy' 'Mosby' 'Maggie' 'Leela' 'Ralphy' 'Brownie' 'Meyer'
 'Stella' 'mad' 'Frank' 'Tonks' 'Lincoln' 'Oakley' 'Dale' 'Rizzo' 'Arnie'
 'Pinot' 'Dallas' 'Hero' 'Frankie' 'Stormy' 'Mairi' 'Loomis' 'Godi' 'Kenny'
 'Deacon' 'Timmy' 'Harper' 'Chipson' 'Combo' 'Dash' 'Bell' 'Hurley' 'Jay'
 'Mya' 'Strider' 'an' 'Wesley' 'Solomon' 'Huck' 'very' 'O' 'Blue' 'Finley'
 'Sprinkles' 'Heinrich' 'Shakespeare' 'Fizz' 'Chip' 'Grey' 'Roosevelt'
 'Gromit' 'Willem' 'Dakota' 'Dixie' 'Al' 'Jackson' 'just' 'Carbon' 'DonDon'
 'Kirby' 'Lou' 'Nollie' 'Chevy' 'Tito' 'Louie' 'Rupert' 'Rufus' 'Brudge'
 'Shadoe' 'Colby' 'Angel' 'Brat' 'Tove' 'my' 'Aubie' 'Kota' 'Eve' 'Glenn'
 'Shelby' 'Sephie' 'Bonaparte' 'Albert' 'Wishes' 'Rose' 'Theo' 'Rocco'
 'Fido' 'Emma' 'Spencer' 'Lilli' 'Boston' 'Brandonald' 'Corey' 'Leonard'
 'Chompsky' 'Beckham' 'Devón' 'Gert' 'Watson' 'Rubio' 'Keith' 'Dex' 'Carly'
 'Ace' 'Tayzie' 'Grizzie' 'Fred' 'Gilbert' 'Zoe' 'Stewie' 'Calvin' 'Lilah'
 'Spanky' 'Jameson' 'Piper' 'Atticus' 'Blu' 'Dietrich' 'Divine' 'Tripp'
 'his' 'Cora' 'Huxley' 'Keurig' 'Bookstore' 'Linus' 'Abby' 'Shaggy'
 'Shiloh' 'Gustav' 'Arlen' 'Percy' 'Lenox' 'Sugar' 'Harvey' 'Blanket'
 'actually' 'Geno' 'Stark' 'Beya' 'Kilo' 'Kayla' 'Maxaroni' 'Doug' 'Edmund'
 'Aqua' 'Theodore' 'Chase' 'getting' 'Rorie' 'Simba' 'Charles' 'Bayley'
 'Axel' 'Storkson' 'Remy' 'Chadrick' 'Kellogg' 'Buckley' 'Livvie' 'Terry'
 'Hermione' 'Ralpher' 'Aldrick' 'this' 'unacceptable' 'Rooney' 'Crystal'
 'Ziva' 'Stefan' 'Pupcasso' 'Puff' 'Flurpson' 'Coleman' 'Enchilada'
 'Raymond' 'all' 'Rueben' 'Cilantro' 'Karll' 'Sprout' 'Blitz' 'Bloop'
 'Lillie' 'Ashleigh' 'Kreggory' 'Sarge' 'Luther' 'Ivar' 'Jangle'
 'Schnitzel' 'Panda' 'Berkeley' 'Ralphé' 'Charleson' 'Clyde' 'Harnold'
 'Sid' 'Pippa' 'Otis' 'Carper' 'Bowie' 'Alexanderson' 'Suki' 'Barclay'
 'Skittle' 'Ebby' 'Flávio' 'Smokey' 'Link' 'Jennifur' 'Ozzy' 'Bluebert'
 'Stephanus' 'Bubbles' 'old' 'Zeus' 'Bertson' 'Nico' 'Michelangelope'
 'Siba' 'Calbert' 'Curtis' 'Travis' 'Thumas' 'Kanu' 'Lance' 'Opie' 'Kane'
 'Olive' 'Chuckles' 'Staniel' 'Sora' 'Beemo' 'Gunner' 'infuriating' 'Lacy'
 'Tater' 'Olaf' 'Cecil' 'Vince' 'Karma' 'Billy' 'Walker' 'Rodney' 'Klevin'
 'Malikai' 'Bobble' 'River' 'Jebberson' 'Remington' 'Farfle' 'Jiminus'
 'Clarkus' 'Finnegus' 'Cupcake' 'Kathmandu' 'Ellie' 'Katie' 'Kara' 'Adele'
 'Zara' 'Ambrose' 'Jimothy' 'Bode' 'Terrenth' 'Reese' 'Chesterson' 'Lucia'
 'Bisquick' 'Ralphson' 'Socks' 'Rambo' 'Rudy' 'Fiji' 'Rilo' 'Bilbo'
 'Coopson' 'Yoda' 'Millie' 'Chet' 'Crouton' 'Daniel' 'Kaia' 'Murphy'
 'Dotsy' 'Eazy' 'Coops' 'Fillup' 'Miley' 'Charl' 'Reagan' 'Yukon' 'CeCe'
 'Cuddles' 'Claude' 'Jessiga' 'Carter' 'Ole' 'Pherb' 'Blipson' 'Reptar'
 'Trevith' 'Berb' 'Bob' 'Colin' 'Brian' 'Oliviér' 'Grady' 'Kobe' 'Freddery'
 'Bodie' 'Dunkin' 'Wally' 'Tupawc' 'Amber' 'Edgar' 'Teddy' 'Kingsley'
 'Brockly' 'Richie' 'Molly' 'Vinscent' 'Cedrick' 'Hazel' 'Lolo' 'Eriq'
 'Phred' 'the' 'Oddie' 'Maxwell' 'Geoff' 'Covach' 'Durg' 'Fynn' 'Ricky'
 'Herald' 'Lucky' 'Ferg' 'Trip' 'Clarence' 'Hamrick' 'Brad' 'Pubert'
 'Frönq' 'Derby' 'Lizzie' 'Ember' 'Blakely' 'Opal' 'Marq' 'Kramer' 'Barry'
 'Gordon' 'Baxter' 'Mona' 'Horace' 'Crimson' 'Birf' 'Hammond' 'Lorelei'
 'Marty' 'Brooks' 'Petrick' 'Hubertson' 'Gerbald' 'Oreo' 'Bruiser' 'Perry'
 'Bobby' 'Jeph' 'Obi' 'Tino' 'Kulet' 'Sweets' 'Lupe' 'Tiger' 'Jiminy'
 'Griffin' 'Banjo' 'Brandy' 'Lulu' 'Darrel' 'Taco' 'Joey' 'Patrick' 'Kreg'
 'Todo' 'Tess' 'Ulysses' 'Toffee' 'Apollo' 'Asher' 'Glacier' 'Chuck'
 'Champ' 'Ozzie' 'Griswold' 'Cheesy' 'Moofasa' 'Hector' 'Goliath' 'Kawhi'
 'by' 'Emmie' 'Penelope' 'Willie' 'Rinna' 'Mike' 'William' 'Dwight' 'Evy'
 'officially' 'Rascal' 'Linda' 'Tug' 'Tango' 'Grizz' 'Jerome' 'Crumpet'
 'Jessifer' 'Izzy' 'Ralph' 'Sandy' 'Humphrey' 'Tassy' 'Juckson' 'Chuq'
 'Tyrus' 'Karl' 'Godzilla' 'Vinnie' 'Kenneth' 'Herm' 'Bert' 'Striker'
 'Donny' 'Pepper' 'Bernie' 'Buddah' 'Lenny' 'Arnold' 'Zuzu' 'Mollie'
 'Laela' 'Tedders' 'Superpup' 'Rufio' 'Jeb' 'Rodman' 'Jonah' 'Chesney'
 'life' 'Henry' 'Bobbay' 'Mitch' 'Kaiya' 'Acro' 'Aiden' 'Obie' 'Dot'
 'Shnuggles' 'Kendall' 'Jeffri' 'Steve' 'Mac' 'Fletcher' 'Kenzie' 'Pumpkin'
 'Schnozz' 'Gustaf' 'Cheryl' 'Ed' 'Leonidas' 'Norman' 'Caryl' 'Scott' 'Taz'
 'Darby' 'Jackie' 'light' 'Jazz' 'Franq' 'Pippin' 'Rolf' 'Snickers'
 'Ridley' 'Cal' 'Bradley' 'Bubba' 'Tuco' 'Patch' 'Mojo' 'Batdog' 'Dylan'
 'space' 'Mark' 'JD' 'Alejandro' 'Scruffers' 'Pip' 'Julius' 'Tanner'
 'Sparky' 'Anthony' 'Holly' 'Jett' 'Amy' 'Sage' 'Andy' 'Mason' 'Trigger'
 'Antony' 'Creg' 'Traviss' 'Gin' 'Jeffrie' 'Danny' 'Ester' 'Pluto' 'Bloo'
 'Edd' 'Willy' 'Herb' 'Damon' 'Peanut' 'Nigel' 'Butters' 'Sandra' 'Fabio'
 'Randall' 'Liam' 'Tommy' 'Ben' 'Raphael' 'Julio' 'Andru' 'Kloey' 'Shawwn'
 'Skye' 'Kollin' 'Ronduh' 'Billl' 'Saydee' 'Dug' 'Tessa' 'Sully' 'Kirk'
 'Ralf' 'Clarq' 'Jaspers' 'Samsom' 'Harrison' 'Chaz' 'Jeremy' 'Jaycob'
 'Lambeau' 'Ruffles' 'Amélie' 'Bobb' 'Banditt' 'Kevon' 'Winifred' 'Hanz'
 'Churlie' 'Zeek' 'Timofy' 'Maks' 'Jomathan' 'Kallie' 'Marvin' 'Spark'
 'Gòrdón' 'Jo' 'DayZ' 'Jareld' 'Torque' 'Ron' 'Skittles' 'Cleopatricia'
 'Erik' 'Stu' 'Tedrick' 'Filup' 'Kial' 'Naphaniel' 'Dook' 'Hall' 'Philippe'
 'Biden' 'Fwed' 'Genevieve' 'Joshwa' 'Bradlay' 'Clybe' 'Keet' 'Carll'
 'Jockson' 'Josep' 'Lugan' 'Christoper']
----------------------------------------------------------------
[ "This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU"
 "This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 https://t.co/0Xxu71qeIV"
 'This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10 https://t.co/wUnZnhtVJB'
 ...,
 'Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would cuddle af https://t.co/y671yMhoiR'
 'This is a western brown Mitsubishi terrier. Upset about leaf. Actually 2 dogs here. 7/10 would walk the shit out of https://t.co/r7mOb2m0UI'
 'Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet https://t.co/BLDqew2Ijj']
----------------------------------------------------------------
[ '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>'
 '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>'
 '<a href="http://vine.co" rel="nofollow">Vine - Make a Scene</a>'
 '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>']

In [13]:
dogsTwitter_archive.isnull().sum()

tweet_id                         0
in_reply_to_status_id         2278
in_reply_to_user_id           2278
timestamp                        0
source                           0
text                             0
retweeted_status_id           2175
retweeted_status_user_id      2175
retweeted_status_timestamp    2175
expanded_urls                   59
rating_numerator                 0
rating_denominator               0
name                             0
doggo                            0
floofer                          0
pupper                           0
puppo                            0
dtype: int64

### Assessment for data 2 - twitter image predictions

In [14]:
dog_images.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null int64
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB

In [15]:
dog_images.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

In [16]:
dog_images.describe()

           tweet_id      img_num      p1_conf       p2_conf       p3_conf
count  2.075000e+03  2075.000000  2075.000000  2.075000e+03  2.075000e+03
mean   7.384514e+17     1.203855     0.594548  1.345886e-01  6.032417e-02
std    6.785203e+16     0.561875     0.271174  1.006657e-01  5.090593e-02
min    6.660209e+17     1.000000     0.044333  1.011300e-08  1.740170e-10
25%    6.764835e+17     1.000000     0.364412  5.388625e-02  1.622240e-02
50%    7.119988e+17     1.000000     0.588230  1.181810e-01  4.944380e-02
75%    7.932034e+17     1.000000     0.843855  1.955655e-01  9.180755e-02
max    8.924206e+17     4.000000     1.000000  4.880140e-01  2.734190e-01

In [17]:
dog_images.isnull().sum()   #no null values

tweet_id    0
jpg_url     0
img_num     0
p1          0
p1_conf     0
p1_dog      0
p2          0
p2_conf     0
p2_dog      0
p3          0
p3_conf     0
p3_dog      0
dtype: int64

### Assessment for data 3 - twitter API datadump

In [18]:
twitter_extractedDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2347 entries, 0 to 2346
Data columns (total 4 columns):
tweet_id         2347 non-null int64
retweet_count    2347 non-null int64
likes            2347 non-null int64
full_text        2347 non-null object
dtypes: int64(3), object(1)
memory usage: 73.4+ KB

In [19]:
twitter_extractedDF.describe()

           tweet_id  retweet_count          likes
count  2.347000e+03    2347.000000    2347.000000
mean   7.424023e+17    3077.372390    8114.887516
std    6.838829e+16    5103.719474   12176.937423
min    6.660209e+17       0.000000       0.000000
25%    6.783846e+17     614.000000    1412.000000
50%    7.189719e+17    1437.000000    3576.000000
75%    7.988157e+17    3585.500000   10071.000000
max    8.924206e+17   78466.000000  141665.000000

In [20]:
twitter_extractedDF.isnull().sum()    #no null values

tweet_id         0
retweet_count    0
likes            0
full_text        0
dtype: int64

In [21]:
twitter_extractedDF.head()

,tweet_id,retweet_count,likes,full_text
0,892420643555336193,8738,39196,This is Phineas. He's a mystical boy. Only eve...
1,892177421306343426,6411,33567,This is Tilly. She's just checking pup on you....
2,891815181378084864,4257,25304,This is Archie. He is a rare Norwegian Pouncin...
3,891689557279858688,8834,42553,This is Darla. She commenced a snooze mid meal...
4,891327558926688256,9617,40741,This is Franklin. He would like you to stop ca...

In [22]:
twitter_extractedDF.tail()

,tweet_id,retweet_count,likes,full_text
2342,666049248165822465,40,110,Here we have a 1949 1st generation vulpix. Enj...
2343,666044226329800704,143,305,This is a purebred Piers Morgan. Loves to Netf...
2344,666033412701032449,46,126,Here is a very happy pup. Big fan of well-main...
2345,666029285002620928,47,131,This is a western brown Mitsubishi terrier. Up...
2346,666020888022790149,523,2530,Here we have a Japanese Irish Setter. Lost eye...

--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
### **Quality Issues:**    
I. **Data 1 - dogsTwitter_archive:**  
        0. The 'text' column is truncated in certain records - replace the text column from the twitter API data dump.  
        1. The dataset has retweets whereas we want only original 'dog' tweets with images. Filter the dataset for enforcing this condition.   
        2. Tweet text contains urls which needs to be cleaned.  
        3. HTML elements in 'source column'.  
        4. Errors in dog names. Some names are 'None'. Some names are listed as smaller case 'not', 'an', etc, which might most probably be wrong.  
        5. Unusual values for rating_numerator and rating_denominator columns. Find the unsual values and fix them if required.   
        6. Convert columns to appropriate datatypes for easier analysis  
            i. tweet_id, in_reply_to_status_id, in_reply_to_user_id, retweeted_status_id, retweeted_status_user_id columns should be categories (i prefer it to be categories rather than strings)  
            ii. retweeted_status_timestamp column should be datetime format.  
        7. Check for 'None' or null values for dog_stage after merging the columns - doggo, floofer, pupper, and pupp  
        8. variation of null data representations in many columns (like 'None', NaN etc). - convert all null values as NaN records 
            
II. **Data 2 - twitter image predictions:**
        1. Convert tweet_id column to category datatype
        2. Missing records - not all tweet_id records are present in the image predicitons file
      
III. **Data 3 - twitter API datadump:**    
        1. Convert into appropriate dtypes:  
            i. 'tweet_id' column to category datatype  
            ii. 'retweet_created_at' column to date_time format   
        2. Missing records - not all tweet_id records are present in the image predicitons file  
          
    

### **Tidiness issues:**      
I. **Data 1 - dogsTwitter_archive:**    
        1. doggo, floofer, pupper, pupp columns should be merged into 1 column to represent the stage of dog.  
     
II. **General for the whole project:**  
        1. Merge all 3 datasets (twitter archive, image predictions and twitter datadump) to form one file for analysis.    
  
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------

## Clean

This section deals with cleaning up (for all quality and tidyness issues listed above) and merging all the gathered datasets which were assessed in the section above.

### Quality Issues:  

### Cleaning for data1 - twitter archive

In [23]:
# making a copy before cleaning
dogsTwitter_archive_original = dogsTwitter_archive.copy()

#### Define

0.. The 'text' column is truncated in certain records  
    The twitter API extracted data dump (data 3) has the full un-truncated text. Replacing the text column in dogsTwitter_archive from the twitter API data dump (twitter_extractedDF).

#### Code

In [24]:
#Suppressing warnings
import warnings
warnings.filterwarnings('ignore')

In [25]:
# Replace the text column in dogsTwitter_archive with full_text column from twitter_extractedDF
for i in range(len(dogsTwitter_archive)):
    for j in range(len(twitter_extractedDF)):
        if (dogsTwitter_archive['tweet_id'].iloc[i] == twitter_extractedDF['tweet_id'].iloc[j]):
            dogsTwitter_archive['text'].iloc[i] = twitter_extractedDF['full_text'].iloc[j]

#### Test

In [26]:
# The text has been replaced with full_text
dogsTwitter_archive['text'].values

array([ "This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU",
       "This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 https://t.co/0Xxu71qeIV",
       'This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10 https://t.co/wUnZnhtVJB',
       ...,
       'Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would cuddle af https://t.co/y671yMhoiR',
       'This is a western brown Mitsubishi terrier. Upset about leaf. Actually 2 dogs here. 7/10 would walk the shit out of https://t.co/r7mOb2m0UI',
       'Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet https://t.co/BLDqew2Ijj'], dtype=object)

#### Define

1.. The dataset has retweets whereas we want only original 'dog' tweets with images. Filter the dataset for enforcing this condition.

#### Code

In [27]:
dogsTwitter_archive.info()

# Select only records which has retweet related column as null. I choose 'retweeted_status_id' for analysis
dogsTwitter_archive = dogsTwitter_archive[pd.isnull(dogsTwitter_archive.retweeted_status_id)]
dogsTwitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2175 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2175 non-null object
source                        2175 non-null object
text                          2175 non-null object
retweeted_status_id           0 non-null float64
retweeted_status_user_id      0 non-null float64
retweeted_status_timestamp    0 non-null object
expanded_urls                 2117 non-null object
rating_numerator              2175 non-null int64
rating_denominator            2175 non-null int64
name                          2175 non-null object
doggo                         2175 non-null object
floofer                       2175 non-null object
pupper                        2175 non-null object
puppo                         2175 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 305.9+ KB

In [28]:
# Dropping retweet related columns.
# Also dropping reply related columns as they don't seem much useful
dogsTwitter_archive = dogsTwitter_archive.drop(['retweeted_status_id', 
                          'retweeted_status_user_id', 
                          'retweeted_status_timestamp',
                          'in_reply_to_status_id',
                          'in_reply_to_user_id'], axis = 1)

In [29]:
# Also dropping the records which does not have an image associated with the tweet

# Checking if there is any link in the text column which could be extracted out.
dogsTwitter_archive.text[dogsTwitter_archive.expanded_urls.isnull()].values

# There are none. Hence dropping these records with no image links
dogsTwitter_archive = dogsTwitter_archive[pd.notnull(dogsTwitter_archive.expanded_urls)]

#### Test

In [30]:
dogsTwitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2117 entries, 0 to 2355
Data columns (total 12 columns):
tweet_id              2117 non-null int64
timestamp             2117 non-null object
source                2117 non-null object
text                  2117 non-null object
expanded_urls         2117 non-null object
rating_numerator      2117 non-null int64
rating_denominator    2117 non-null int64
name                  2117 non-null object
doggo                 2117 non-null object
floofer               2117 non-null object
pupper                2117 non-null object
puppo                 2117 non-null object
dtypes: int64(3), object(9)
memory usage: 215.0+ KB

#### Define

2.. Tweet text contains urls which needs to be cleaned.

Not all text in the twitter archive has an image url associated with the text (This could have been thought of as a tidiness issue but since I am just removing the links and not making separate columns for it, I am considering it as a quality issue)

#### Code

In [31]:
print(dogsTwitter_archive['text'].values)

[ "This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU"
 "This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 https://t.co/0Xxu71qeIV"
 'This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10 https://t.co/wUnZnhtVJB'
 ...,
 'Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would cuddle af https://t.co/y671yMhoiR'
 'This is a western brown Mitsubishi terrier. Upset about leaf. Actually 2 dogs here. 7/10 would walk the shit out of https://t.co/r7mOb2m0UI'
 'Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet https://t.co/BLDqew2Ijj']

In [32]:
cleaned_text = np.ndarray(shape=(len(dogsTwitter_archive),), dtype=object)

for index in range(len(dogsTwitter_archive)):
    #find if the text has a link.  If so extract and remove it
    link_index = dogsTwitter_archive['text'].iloc[index].find('http')
    if (link_index > 0):
        cleaned_text[index] = (dogsTwitter_archive['text'].iloc[index])[0:dogsTwitter_archive['text'].iloc[index].find('http')]
    else:
        # If no link present in text, retain the whole text
        cleaned_text[index] = dogsTwitter_archive['text'].iloc[index]

dogsTwitter_archive['text'] = cleaned_text

#### Test

In [33]:
dogsTwitter_archive['text'].values

# Now the text column does not have any embedded links. I found most of the links broken and hence cleaning this up would improve the quality 
# of this column

# Ideally the ratings should also be removed as part of tidiness but since there sometimes are multiple ratings in the 
# text, I am keeping it for future work.

array([ "This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 ",
       "This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 ",
       'This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10 ',
       ...,
       'Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would cuddle af ',
       'This is a western brown Mitsubishi terrier. Upset about leaf. Actually 2 dogs here. 7/10 would walk the shit out of ',
       'Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet '], dtype=object)

#### Define

 3.. HTML elements in 'source column'.

#### Code

In [34]:
dogsTwitter_archive['source'].value_counts()

<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>     1985
<a href="http://vine.co" rel="nofollow">Vine - Make a Scene</a>                          91
<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>                       30
<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>      11
Name: source, dtype: int64

In [35]:
cleaned_source = dogsTwitter_archive['source'].str.findall('>(.*)<')

In [36]:
# replacing the 'source' column with the new cleaned_source' values
dogsTwitter_archive['source'] = cleaned_source

#### Test

In [37]:
#testing
dogsTwitter_archive.info()
dogsTwitter_archive['source']

# The source column is now cleaned of the html embeddings.

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2117 entries, 0 to 2355
Data columns (total 12 columns):
tweet_id              2117 non-null int64
timestamp             2117 non-null object
source                2117 non-null object
text                  2117 non-null object
expanded_urls         2117 non-null object
rating_numerator      2117 non-null int64
rating_denominator    2117 non-null int64
name                  2117 non-null object
doggo                 2117 non-null object
floofer               2117 non-null object
pupper                2117 non-null object
puppo                 2117 non-null object
dtypes: int64(3), object(9)
memory usage: 215.0+ KB

0       [Twitter for iPhone]
1       [Twitter for iPhone]
2       [Twitter for iPhone]
3       [Twitter for iPhone]
4       [Twitter for iPhone]
5       [Twitter for iPhone]
6       [Twitter for iPhone]
7       [Twitter for iPhone]
8       [Twitter for iPhone]
9       [Twitter for iPhone]
10      [Twitter for iPhone]
11      [Twitter for iPhone]
12      [Twitter for iPhone]
13      [Twitter for iPhone]
14      [Twitter for iPhone]
15      [Twitter for iPhone]
16      [Twitter for iPhone]
17      [Twitter for iPhone]
18      [Twitter for iPhone]
20      [Twitter for iPhone]
21      [Twitter for iPhone]
22      [Twitter for iPhone]
23      [Twitter for iPhone]
24      [Twitter for iPhone]
25      [Twitter for iPhone]
26      [Twitter for iPhone]
27      [Twitter for iPhone]
28      [Twitter for iPhone]
29      [Twitter for iPhone]
31      [Twitter for iPhone]
                ...
2326    [Twitter for iPhone]
2327    [Twitter for iPhone]
2328    [Twitter for iPhone]
2329    [Twitter for iPhone]
2330    [Twitter for iPhone]
2331    [Twitter for iPhone]
2332    [Twitter for iPhone]
2333    [Twitter for iPhone]
2334    [Twitter for iPhone]
2335    [Twitter for iPhone]
2336    [Twitter for iPhone]
2337    [Twitter for iPhone]
2338    [Twitter for iPhone]
2339    [Twitter for iPhone]
2340    [Twitter for iPhone]
2341    [Twitter for iPhone]
2342    [Twitter for iPhone]
2343    [Twitter for iPhone]
2344    [Twitter for iPhone]
2345    [Twitter for iPhone]
2346    [Twitter for iPhone]
2347    [Twitter for iPhone]
2348    [Twitter for iPhone]
2349    [Twitter for iPhone]
2350    [Twitter for iPhone]
2351    [Twitter for iPhone]
2352    [Twitter for iPhone]
2353    [Twitter for iPhone]
2354    [Twitter for iPhone]
2355    [Twitter for iPhone]
Name: source, Length: 2117, dtype: object

#### 'Source' column could be further cleaned by extracting the source name itself (E.g., iPhone). But I see that most of the times, it was iPhone only and hence doesn't seem to be useful.

#### Define

4.. Errors in dog names.

#### Code

In [38]:
print(dogsTwitter_archive['name'])

0        Phineas
1          Tilly
2         Archie
3          Darla
4       Franklin
5           None
6            Jax
7           None
8           Zoey
9         Cassie
10          Koda
11         Bruno
12          None
13           Ted
14        Stuart
15        Oliver
16           Jim
17          Zeke
18       Ralphus
20        Gerald
21       Jeffrey
22          such
23        Canela
24          None
25          None
26          Maya
27        Mingus
28         Derek
29        Roscoe
31       Waffles
          ...
2326       quite
2327           a
2328        None
2329        None
2330        None
2331        None
2332        None
2333          an
2334           a
2335          an
2336        None
2337        None
2338        None
2339        None
2340        None
2341        None
2342        None
2343        None
2344        None
2345         the
2346         the
2347           a
2348           a
2349          an
2350           a
2351        None
2352           a
2353           a
2354           a
2355        None
Name: name, Length: 2117, dtype: object

In [39]:
# Make a set of dog_names which is wrong (set preferred to have no duplicates)
not_names = set(['a', 'an', 'the', 'quite', 'such'])

# There might be much more of these. Hence extracting names which starts with lower case letters or single letters
for name in dogsTwitter_archive['name']:
    if (name[0].islower() or len(name) < 2):
        # Add name if not already present in set
        not_names.add(name)

print(not_names)

{'by', 'his', 'just', 'this', 'quite', 'infuriating', 'incredibly', 'space', 'officially', 'a', 'light', 'not', 'getting', 'such', 'the', 'old', 'one', 'O', 'unacceptable', 'all', 'mad', 'actually', 'my', 'an', 'life', 'very'}

In [40]:
# before programmatically cleaning the code, I am interested in seeing what the name of the dog(s) to be 'O' as given in the list above.
for index in range(len(dogsTwitter_archive)):
    if dogsTwitter_archive['name'].iloc[index] == 'O':
        print(dogsTwitter_archive.values[index], index)

[776201521193218049 '2016-09-14 23:30:38 +0000'
 list(['Twitter for iPhone'])
 "This is O'Malley. That is how he sleeps. Doesn't care what you think about it. 10/10 comfy af "
 'https://twitter.com/dog_rates/status/776201521193218049/photo/1' 10 10
 'O' 'None' 'None' 'None' 'None'] 596

In [41]:
# Interestingly, there is only one recod and the actual dog name is O'Malley. I do not know if correcting this programmatically is worth it. Hence, correcting it manually
dogsTwitter_archive['name'].iloc[index] = "O'Malley"

#Testing
print(dogsTwitter_archive['name'].iloc[index])

O'Malley

In [42]:
# replace the name as 'NaN' for the names in set not_names     
for index in range(len(dogsTwitter_archive)):
    if dogsTwitter_archive['name'].iloc[index] in not_names:
        dogsTwitter_archive['name'].iloc[index] = np.NaN
print(dogsTwitter_archive['name'])

0        Phineas
1          Tilly
2         Archie
3          Darla
4       Franklin
5           None
6            Jax
7           None
8           Zoey
9         Cassie
10          Koda
11         Bruno
12          None
13           Ted
14        Stuart
15        Oliver
16           Jim
17          Zeke
18       Ralphus
20        Gerald
21       Jeffrey
22           NaN
23        Canela
24          None
25          None
26          Maya
27        Mingus
28         Derek
29        Roscoe
31       Waffles
          ...
2326         NaN
2327         NaN
2328        None
2329        None
2330        None
2331        None
2332        None
2333         NaN
2334         NaN
2335         NaN
2336        None
2337        None
2338        None
2339        None
2340        None
2341        None
2342        None
2343        None
2344        None
2345         NaN
2346         NaN
2347         NaN
2348         NaN
2349         NaN
2350         NaN
2351        None
2352         NaN
2353         NaN
2354         NaN
2355    O'Malley
Name: name, Length: 2117, dtype: object

In [43]:
# Also replace all the existing 'None' values to NaN values
for index in range(len(dogsTwitter_archive)):
    if dogsTwitter_archive['name'].iloc[index] == 'None':
        dogsTwitter_archive['name'].iloc[index] = np.NaN
print(dogsTwitter_archive['name'])

0        Phineas
1          Tilly
2         Archie
3          Darla
4       Franklin
5            NaN
6            Jax
7            NaN
8           Zoey
9         Cassie
10          Koda
11         Bruno
12           NaN
13           Ted
14        Stuart
15        Oliver
16           Jim
17          Zeke
18       Ralphus
20        Gerald
21       Jeffrey
22           NaN
23        Canela
24           NaN
25           NaN
26          Maya
27        Mingus
28         Derek
29        Roscoe
31       Waffles
          ...
2326         NaN
2327         NaN
2328         NaN
2329         NaN
2330         NaN
2331         NaN
2332         NaN
2333         NaN
2334         NaN
2335         NaN
2336         NaN
2337         NaN
2338         NaN
2339         NaN
2340         NaN
2341         NaN
2342         NaN
2343         NaN
2344         NaN
2345         NaN
2346         NaN
2347         NaN
2348         NaN
2349         NaN
2350         NaN
2351         NaN
2352         NaN
2353         NaN
2354         NaN
2355    O'Malley
Name: name, Length: 2117, dtype: object

In [44]:
# Now, for the names 'NaN', we have to check if there is actually a name for the dog in the 'text' column
for index in range(len(dogsTwitter_archive)):
    if dogsTwitter_archive['name'].isnull().iloc[index]:
        print(dogsTwitter_archive['text'].iloc[index])

# Some of them do have names!
## Some keywords which could be used to extract names from 'text' column
# 'name is' 
# not 'this is a' (visual inspection tells me this usually specifies breed name) 
# word after this is (upper or lower case) but not 'this is a' or 'this is an'
# Starts with uppercase name {e.g., Name is but name not equal to This (to avoid This is)) 
# Name's

Here we have a majestic great white breaching off South Africa's coast. Absolutely h*ckin breathtaking. 13/10 (IG: tucker_marlo) #BarkWeek
When you watch your owner call another dog a good boy but then they turn back to you and say you're a great boy. 13/10
Here's a puppo that seems to be on the fence about something haha no but seriously someone help her. 13/10
I've yet to rate a Venezuelan Hover Wiener. This is such an honor. 14/10 paw-inspiring af (IG: roxy.thedoxy)
You may not have known you needed to see this today. 13/10 please enjoy (IG: emmylouroo)
This... is a Jubilant Antarctic House Bear. We only rate dogs. Please only send dogs. Thank you... 12/10 would suffocate in floof
I have a new hero and his name is Howard. 14/10
Here we have a corgi undercover as a malamute. Pawbably doing important investigative work. Zero control over tongue happenings. 13/10
I present to you, Pup in Hat. Pup in Hat is great for all occasions. Extremely versatile. Compact as h*ck. 14/10 (IG: itselizabethgales)
OMG HE DIDN'T MEAN TO HE WAS JUST TRYING A LITTLE BARKOUR HE'S SUPER SORRY 13/10 WOULD FORGIVE IMMEDIATE
Please only send dogs. We don't rate mechanics, no matter how h*ckin good. Thank you... 13/10 would sneak a pat
Here is a pupper approaching maximum borkdrive. Zooming at never before seen speeds. 14/10 paw-inspiring af
(IG: puffie_the_chow)
Ugh not again. We only rate dogs. Please don't send in well-dressed  floppy-tongued street penguins. Dogs only please. Thank you... 12/10
Please don't send in photos without dogs in them. We're not @porch_rates. Insubordinate and churlish. Pretty good porch tho 11/10
Martha is stunning how h*ckin dare you. 13/10
I can say with the pupmost confidence that the doggos who assisted with this search are heroic as h*ck. 14/10 for all
You'll get your package when that precious man is done appreciating the pups. 13/10 for everyone
Guys please stop sending pictures without any dogs in th- oh never mind hello excuse me sir. 12/10 stealthy as h*ck
I can't believe this keeps happening. This, is a birb taking a bath. We only rate dogs. Please only send dogs. Thank you... 12/10
We usually don't rate Deck-bound Saskatoon Black Bears, but this one is h*ckin flawless. Sneaky tongue slip too. 13/10 would hug firmly
Here's a very large dog. He has a date later. Politely asked this water person to check if his breath is bad. 12/10 good to go doggo
Here are my favorite #dogsatpollingstations
Most voted for a more consistent walking schedule and to increase daily pats tenfold. All 13/10
We. Only. Rate. Dogs. Do not send in other things like this fluffy floor shark clearly ready to attack. Get it together guys... 12/10
Never doubt a doggo 14/10
Real funny guys. Sending in a pic without a dog in it. Hilarious. We'll rate the rug tho because it's giving off a very good vibe. 11/10
Here's a h*ckin peaceful boy. Unbothered by the comings and goings. 13/10 please reveal your wise ways
Unbelievable. We only rate dogs. Please don't send in non-canines like the "I" from Pixar's opening credits. Thank you... 12/10
Oh my this spooked me up. We only rate dogs, not happy ghosts. Please send dogs only. It's a very simple premise. Thank you... 13/10
He was providing for his family 13/10 how dare you
We only rate dogs. Please don't send in Jesus. We're trying to remain professional and legitimate. Thank you... 14/10
Ladies and gentlemen... I found Pipsy. He may have changed his name to Pablo, but he never changed his love for the sea. Pupgraded to 14/10
We only rate dogs. Please don't send perfectly toasted marshmallows attempting to drive. Thank you... 13/10
HI. MY. NAME. IS. BOOMER. AND. I. WANT. TO. SAY. IT'S. H*CKIN. RIDICULOUS. THAT. DOGS. CAN'T VOTE. ABSOLUTE. CODSWALLUP. THANK. YOU. 13/10
Here we have perhaps the wisest dog of all. Above average with light sabers. Immortal as h*ck. 14/10 dog, or dog not, there is no try
Sorry for the lack of posts today. I came home from school and had to spend quality time with my puppo. Her name is Zoey and she's 13/10
We only rate dogs. This is quite clearly a smol broken polar bear. We'd appreciate if you only send dogs. Thank you... 12/10
Here we have an exotic dog. Good at ukulele. Fashionable af. Has two more arms if needed. Is blue. Knows what 'ohana means. 13/10 would pet
I have stumbled puppon a doggo painting party. They're looking to be the next Pupcasso or Puppollock. All 13/10 would put it on the fridge
Instead of the usual nightly dog rate, I'm sharing this story with you. Meeko is 13/10 and would like your help


THIS IS CHARLIE, MARK. HE DID JUST WANT TO SAY HI AFTER ALL. PUPGRADED TO A 14/10. WOULD BE AN HONOR TO FLY WITH
HE'S LIKE "WAIT A MINUTE I'M AN ANIMAL THIS IS AMAZING HI HUMAN I LOVE YOU AS WELL" 13/10
Here's a puppo participating in the #ScienceMarch. Cleverly disguising her own doggo agenda. 13/10 would keep the planet habitable for
I HEARD HE TIED HIS OWN BOWTIE MARK AND HE JUST WANTS TO SAY HI AND MAYBE A NOGGIN PAT SHOW SOME RESPECT 13/10
Guys, we only rate dogs. This is quite clearly a bulbasaur. Please only send dogs. Thank you... 12/10 human used pet, it's super effective
Sometimes you guys remind me just how impactful a pupper can be. Cooper will be remembered as a good boy by so many. 14/10 rest easy friend
At first I thought this was a shy doggo, but it's actually a Rare Canadian Floofer Owl. Amateurs would confuse the two. 11/10 only send dogs
A photographer took pictures before and after he told his bunny he's a good boy. Here are the results. 13/10
Oh jeez u did me quite the spook little fella. We normally don't rate triceratops but this one seems suspiciously good. 11/10 would pet well
Seriously guys? Again? We only rate dogs. Please stop submitting other things like this super good hammerhead shark. Thank you... 12/10
At first I thought this was a dog because of the sign, but it is clearly Wilson from Home Improvement. Please only send in dogs... 11/10
Please stop sending in animals other than dogs. We only rate dogs. Not Furry Ecuadorian Sea Turtles. Thank you... 12/10
Unbelievable... We. Only. Rate. Dogs. Please stop sending in other things like this Blossoming Flop Kangaroo. Thank you... 11/10
THIS WAS NOT HIS FAULT HE HAD NO IDEA. 11/10 STILL A VERY GOOD DOG
SHE DID AN ICY ZOOM AND KNEW WHEN TO PUT ON THE BRAKES 13/10 CANCEL THE GAME THIS IS ALL WE NEED
We usually don't rate polar bears but this one seems extra good. Majestic as h*ck. 13/10 would hug for a while
C'mon guys. Please only send in dogs. We only rate dogs, not Exceptional-Tongued Peruvian Floor Bears. Thank you... 12/10
PUPDATE: I'm proud to announce that Toby is 236 days sober. Pupgraded to a 13/10. We're all very proud of you, Toby
HE WAS DOING A SNOOZE NO SHAME IN A SNOOZE 13/10
Here we have some incredible doggos for #K9VeteransDay. All brave as h*ck. Salute your dog in solidarity. 14/10 for all
We don't rate penguins, but if we did, this one would get 12/10
I didn't even have to intervene. Took him 4 minutes to realize his error. 10/10 for Kevin
You have been visited by the magical sugar jar puggo. He has granted you three boops. 13/10 would use immediately
SHE MISPLACED HER HOOMAN 13/10 MISTAKES HAPPEN
Here's a pupper before and after being asked "who's a good girl?" Unsure as h*ck. 12/10 hint hint it's you
Atlas is back and this time he's prettier than the sunset. Seems to be aware of it too. 13/10 would give modeling contract
We only rate dogs. Please don't send in any non-canines like this Floppy Tongued House Panda. Thank you... 12/10 would still pet
When you're so blinded by your systematic plagiarism that you forget what day it is. 0/10
Here's a doggo fully pupared for a shower. H*ckin exquisite balance. Sneaky tongue slip too. 13/10
DOGGO ON THE LOOSE I REPEAT DOGGO ON THE LOOSE 10/10
Prosperous good boy 13/10 socioeconomic af
There's going to be a dog terminal at JFK Airport. This is not a drill. 10/10

I usually only share these on Friday's, but this is Blue. He's a very smoochable pooch who needs your help. 13/10


I couldn't make it to the #WKCDogShow BUT I have people there on the ground relaying me the finest pupper pics possible. 13/10 for all
Here's a stressed doggo. Had a long day. Many things on her mind. The hat communicates these feelings exquisitely. 11/10
Occasionally, we're sent fantastic stories. This is one of them. 14/10 for Grace
We only rate dogs. Please don't send in any more non-dogs like this Wild Albanian Street Moose. Thank you... 11/10
Here's a little more info on Dew, your favorite roaming doggo that went h*ckin viral. 13/10

Here's a very loving and accepting puppo. Appears to have read her Constitution well. 14/10 would pat head approvingly
Retweet the h*ck out of this 13/10 pupper #BellLetsTalk
"I wish we were dogs" 14/10 for @BadlandsNPS
Here's a super supportive puppo participating in the Toronto  #WomensMarch today. 13/10
Please stop sending in non-canines like this Very Pettable Dozing Bath Tortoise. We only rate dogs. Only send dogs... 12/10
We only rate dogs. Please don't send pics of men capturing low level clouds. Thank you... 11/10
Here's a doggo who looks like he's about to give you a list of mythical ingredients to go collect for his potion. 11/10 would obey
The floofs have been released I repeat the floofs have been released. 84/70
We are proud to support @LoveYourMelon on their mission to put a hat on every kid battling cancer. They are 14/10


I've never wanted to go to a camp more in my entire life. 12/10 for all on board
Here we have a doggo who has messed up. He was hoping you wouldn't notice. 11/10 someone help him
Some happy pupper news to share. 10/10 for everyone involved

Looks like he went cross-eyed trying way too hard to use the force. 12/10

Name a more iconic quartet... I'll wait. 13/10 for all
Here's a pupper with squeaky hiccups. Please enjoy. 13/10
Happy New Year from the squad! 13/10 for all
Here's a doggo who has concluded that Christmas is entirely too bright. Requests you tone it down a notch. 11/10
We only rate dogs. Please don't send in other things like this very good Christmas tree. Thank you... 13/10
Everybody stop what you're doing and look at this dog with her tiny Santa hat. 13/10
Here's an anonymous doggo that appears to be very done with Christmas. 11/10 cheer up pup
I'm happy to inform you all that Jake is in excellent hands. 13/10 for him and his new family

Please only send in dogs. We only rate dogs, not seemingly heartbroken ewoks. Thank you... still 10/10 would console
I call this one "A Blep by the Sea" 12/10
Here's a pupper in a onesie. Quite pupset about it. Currently plotting revenge. 12/10 would rescue
Here we have Burke (pupper) and Dexter (doggo). Pupper wants to be exactly like doggo. Both 12/10 would pet at same time
"Good afternoon class today we're going to learn what makes a good boy so good" 13/10
Hooman catch successful. Massive hit by dog. Fumble ensued. Possession to dog. 13/10
We only rate dogs. Please stop sending in non-canines like this Freudian Poof Lion. This is incredibly frustrating... 11/10
HE'S TRYING TO BE HIS OWN PERSON LET HIM GO 13/10

Pupper hath acquire enemy. 13/10
Like doggo, like pupper version 2. Both 11/10
oh h*ck 10/10
Here's a very sleepy pupper. Appears to be portable as h*ck. 12/10 would snug intensely
Here's a doggo doin a struggle. 11/10 much determined
Here's a helicopter pupper. He takes off at random. H*ckin hard to control. 12/10 rare af
Here's a sleepy doggo that requested some assistance. 12/10 would carry everywhere
#ImWithThor 13/10

I didn't believe it at first but now I can see that voter fraud is a serious h*ckin issue. 11/10
Elder doggo does a splash. Both 13/10 incredible stuff
Oh h*ck look at this spookling right here. Fright level off the charts. 12/10 sufficiently spooked
Your favorite squad is looking extra h*ckin spooky today. 13/10 for all
Here is a perfect example of someone who has their priorities in order. 13/10 for both owner and Forrest
Vine will be deeply missed. This was by far my favorite one. 14/10
When she says you're a good boy and you know you're a good boy because you're a good boy. 13/10
HE WAS JUST A LIL SLEEPY FROM BEING SUCH A GOOD DOGGI ALL THE TIME MISTAKES HAPPEN 13/10

Atlas is back and this time he's got doggles. Still 13/10 solarly conscious af
Did... did they pick out that license plate? 12/10 for both
"Honestly Kathleen I just want more Ken Bone" 12/10
Who keeps sending in pictures without dogs in them? This needs to stop. 5/10 for the mediocre road
Idk why this keeps happening. We only rate dogs. Not Bangladeshi Couch Chipmunks. Please only send dogs... 12/10
Pupper butt 1, Doggo 0. Both 12/10
We normally don't rate lobsters, but this one appears to be a really good lobster. 10/10 would pet with caution
I want to finally rate this iconic puppo who thinks the parade is all for him. 13/10 would absolutely attend
Here's a perturbed super floof. 12/10 would snug so damn well
We only rate dogs. Pls stop sending in non-canines like this Urban Floof Giraffe. I can't handle this. 11/10
Here's a doggo questioning his entire existence. 10/10 someone tell him he's a good boy
Have you ever seen such a smol pupper? Portable af. 12/10 would keep in shirt pocket
Everybody drop what you're doing and look at this dog. 13/10 must be super h*ckin rare
Oh my god it's Narcos but Barkos. 13/10 someone please make this happen

RIP Loki. Thank you for the good times. You will be missed by many. 14/10
Evolution of a pupper yawn featuring Max. 12/10 groundbreaking stuff
"Yep... just as I suspected. You're not flossing." 12/10 and 11/10 for the pup not flossing
Atlas rolled around in some chalk and now he's a magical rainbow floofer. 13/10 please never take a bath
This is O'Malley. That is how he sleeps. Doesn't care what you think about it. 10/10 comfy af
I can't tap the screen to make the hearts appear fast enough. 10/10 for the source of all future unproductiveness
This girl straight up rejected a guy because he doesn't like dogs. She is my hero and I give her 13/10
I WAS SENT THE ACTUAL DOG IN THE PROFILE PIC BY HIS OWNER THIS IS SO WILD. 14/10 ULTIMATE LEGEND STATUS
You need to watch these two doggos argue through a cat door. Both 11/10
Guys this is getting so out of hand. We only rate dogs. This is a Galapagos Speed Panda. Pls only send dogs... 10/10
Here's a couple rufferees making sure all the sports are played fairly today. Both 10/10 would bribe with extra pets
Doggo will persevere. 13/10

Another pic without a dog in it? What am I supposed to do? Rate the carpet? Fine I will. 7/10 looks adequately comfy
We only rate dogs. Pls stop sending in non-canines like this Arctic Floof Kangaroo. This is very frustrating. 11/10
I don't know any of the backstory behind this picture but for some reason I'm crying. 13/10 for owner and doggo
This is my dog. Her name is Zoey. She knows I've been rating other dogs. She's not happy. 13/10 no bias at all
This left me speechless. 14/10 heckin heroic af
Guys.. we only rate dogs. Pls don't send any more pics of the Loch Ness Monster. Only send in dogs. Thank you. 11/10
Ohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboy. 10/10 for all (by happytailsresort)
Doggo want what doggo cannot have. Temptation strong, dog stronger. 12/10
Here's a wicked fast pupper. 12/10 camera could barely keep pup
We only rate dogs... this is a Taiwanese Guide Walrus. Im getting real heckin tired of this. Please send dogs. 10/10
No no no this is all wrong. The Walmart had to have run into the dog driving the car. 10/10 someone tell him it's ok

This doggo is just waiting for someone to be proud of her and her accomplishment. 13/10 legendary af
Why does this never happen at my front door... 165/150
In case you haven't seen the most dramatic sneeze ever... 13/10
Teagan reads entire books in store so they're free. Loved 50 Shades of Grey (how dare I make that joke so late) 9/10
Here's another picture without a dog in it. Idk why you guys keep sending these. 4/10 just because that's a neat rug
She walks herself up and down the train to be petted by all the passengers. 13/10 I can't handle this
Here's a doggo completely oblivious to the double rainbow behind him. 10/10 someone tell him
All hail sky doggo. 13/10 would jump super high to pet
Pwease accept dis rose on behalf of dog. 11/10
Here's a heartwarming scene of a single father raising his two pups. Downright awe-inspiring af. 12/10 for everyone
When ur older siblings get to play in the deep end but dad says ur not old enough. Maybe one day puppo. All 10/10
Here's a frustrated pupper attempting to escape a pool of Frosted Flakes. 12/10
This is one of the most inspirational stories I've ever come across. I have no words. 14/10 for both doggo and owner
When you hear your owner say they need to hatch another egg, but you've already been on 17 walks today. 10/10
"The dogtor is in hahahaha no but seriously I'm very qualified and that tumor is definitely malignant" 10/10
Here we are witnessing an isolated squad of bouncing doggos. Unbelievably rare for this time of year. 11/10 for all
So this just changed my life. 13/10 please enjoy
Nothing better than a doggo and a sunset. 10/10 majestic af
Hooman used Pokeball
*wiggle*
*wiggle*
Doggo broke free
10/10
Here are three doggos completely misjudging an airborne stick. Decent efforts tho. All 9/10
Hopefully this puppo on a swing will help get you through your Monday. 11/10 would push
Here's a doggo trying to catch some fish. 8/10 futile af (vid by @KellyBauerx)
Please stop sending it pictures that don't even have a doggo or pupper in them. Churlish af. 5/10 neat couch tho
Here's a pupper that's very hungry but too lazy to get up and eat. 12/10 (vid by @RealDavidCortes)
"This photographer took pics of her best friend before and after she told them they were beautiful" 12/10
And finally, happy 4th of July from the squad 🇺🇸 13/10 for all
Pause your cookout and admire this pupper's nifty hat. 10/10
Duuun dun... duuun dun... dunn  dun. dunn dun. dun dun dun dun dun dun dun dun dun dun dun dun dun dun dun. 10/10
What jokester sent in a pic without a dog in it? This is not @rock_rates. This is @dog_rates. Thank you ...10/10
#BarkWeek is getting rather heckin terrifying over here. Doin me quite the spooken. 13/10 (vid by @corgi_zero)

That is Quizno. This is his beach. He does not tolerate human shenanigans on his beach. 10/10 reclaim ur land doggo
This is one of the most reckless puppers I've ever seen. How she got a license in the first place is beyond me. 6/10
"So... we meat again" (I'm so sorry for that pun I couldn't resist pls don't unfollow) 10/10
SWIM AWAY PUPPER SWIM AWAY 13/10 #BarkWeek
This sherk must've leapt out of the water and into the canoe, trapping the human. Won't even help paddle smh. 7/10
Stop what you're doing and watch this heckin masterpiece right here. Both 13/10
PUPPER NOOOOO BEHIND YOUUU 10/10 pls keep this pupper in your thoughts
Pls don't send more sherks. I don't care how seemingly floofy they are. It does me so much frighten. Thank u. 11/10
This is a mighty rare blue-tailed hammer sherk. Human almost lost a limb trying to take these. Be careful guys. 8/10
Viewer discretion is advised. This is a terrible attack in progress. Not even in water (tragic af). 4/10 bad sherk
Again w the sharks guys. This week is about dogs ACTING or DRESSING like sharks. NOT actual sharks. Thank u ...11/10
Guys pls stop sending actual sharks. It's too dangerous for me and the people taking the photos. Thank you ...10/10
Never seen a shark hold another shark like this before. Must be evolving. Both 10/10 please only send dogs though
Guys... I said DOGS with "shark qualities" or "costumes." Not actual sharks. This did me a real frighten ...11/10
PUPDATE: can't see any. Even if I could, I couldn't reach them to pet. 0/10 much disappointment
This is a carrot. We only rate dogs. Please only send in dogs. You all really should know this by now ...11/10
Guys... Dog Jesus 2.0
13/10 buoyant af
When you just can't resist... 10/10 topnotch tongue
Here's a golden floofer helping with the groceries. Bed got in way. Still 11/10 helpful af (vid by @categoen)
This is an Iraqi Speed Kangaroo. It is not a dog. Please only send in dogs. I'm very angry with all of you ...9/10
We only rate dogs. Pls stop sending in non-canines like this Jamaican Flop Seal. This is very very frustrating. 9/10
Here's a doggo realizing you can stand in a pool. 13/10 enlightened af (vid by Tina Conrad)
This is actually a pupper and I'd pet it so well. 12/10

When you're given AUX cord privileges from the back seat and accidentally start blasting an audiobook... both 10/10
This is a very rare Great Alaskan Bush Pupper. Hard to stumble upon without spooking. 12/10 would pet passionately
For anyone who's wondering, this is what happens after a doggo catches it's tail... 11/10
Was just informed about this hero pupper and others like her. Another 14/10, would be an absolute honor to pet
When your crush won't pay attention to you. Both 10/10 tragic af
This is just downright precious af. 12/10 for both pupper and doggo
Here we are witnessing the touchdown of a pupnado. It's not funny it's actually very deadly. 9/10 might still pet
After so many requests, this is Bretagne. She was the last surviving 9/11 search dog, and our second ever 14/10. RIP
When the photographer forgets to tell you where to look... 10/10
This is getting incredibly frustrating. This is a Mexican Golden Beaver. We only rate dogs. Only send dogs ...10/10
Here's a doggo that don't need no human. 12/10 independent af (vid by @MichelleLiuCee)
This... is a Tyrannosaurus rex. We only rate dogs. Please only send in dogs. Thank you ...10/10
Here's a doggo blowing bubbles. It's downright legendary. 13/10 would watch on repeat forever (vid by Kent Duryee)
When a single soap orb changes your entire perception of the universe... 10/10
"Don't talk to me or my son ever again" ...10/10 for both
For the last time, we only rate dogs. Pls stop sending other animals like this Duck-Billed Platypus. Thank you. 9/10
We only rate dogs. Pls stop sending in non-canines like this Slovak Car Bunny. It makes my job very difficult. 11/10
Just wanted to share this super rare Rainbow Floofer in case you guys haven't seen it yet. 13/10 colorful af
Everybody stop what you're doing and watch these puppers enjoy summer. Both 13/10
Say hello to mad pupper. You know what you did. 13/10 would pet until no longer furustrated
We only rate dogs. Please stop sending in non-canines like this Alaskan Flop Turtle. This is very frustrating. 10/10
Right after you graduate vs when you remember you're on your own now and can barely work a washing machine ...10/10
*faints* 12/10 perfection in pupper form
We only rate dogs. Please stop sending in your 31 year old sons that won't get out of your house. Thank you... 11/10
This dog is more successful than I will ever be. 13/10 absolute legend
When your friend is turnt af and you're just trying to chill. 10/10 (vid by @presgang)
"Ello this is dog how may I assist" ...10/10
Like father (doggo), like son (pupper). Both 12/10
When your teacher agreed on 10,000 RTs and no final but after 24 hours you only have 37... 10/10
Say hello to this unbelievably well behaved squad of doggos. 204/170 would try to pet all at once
We only rate dogs. Pls stop sending non-canines like this Bulgarian Eyeless Porch Bear. This is unacceptable... 9/10
"Challenge completed"
(pupgraded to 12/10)
"Challenge accepted"
10/10
When you're way too slow for the "down low" portion of a high five. 13/10
This is all I want in my life. 12/10 for super sleepy pupper
Here's a doggo struggling to cope with the winds. 13/10
This pupper had to undergo emergency haircut surgery so he could hear again. 10/10 miraculous af
This pupper was about to explain where that dirt came from but then decided against it. 11/10
I swear to god if we get sent another Blue Madagascan Peacock we'll deactivate. We 👏 Only 👏 Rate 👏 Dogs... 9/10
When you're trying to enjoy yourself but end up having to take care of your way too drunk friend. 11/10
I'm getting super heckin frustrated with you all sending in non canines like this ostrich. We only rate dogs... 9/10
Pup had to be removed cuz it wouldn't have been fair to the opposing team. 13/10 absolute legend ⚽️

Nothin better than a doggo and a sunset. 11/10
Happy 4/20 from the squad! 13/10 for all
Garden's coming in nice this year. 10/10
This doggo was initially thrilled when she saw the happy cartoon pup but quickly realized she'd been deceived. 10/10
We normally don't rate marshmallows but this one appears to be flawlessly toasted so I'll make an exception. 10/10
Get you a pup that can do both. 10/10
This pic is old but I hadn't seen it until today and had to share. Creative af. 13/10 very good boy, would pet well
Here's a badass mystery pupper. You weren't aware that you owe him money, but you do. 10/10 shades sick af
People please. This is a Deadly Mediterranean Plop T-Rex. We only rate dogs. Only send in dogs. Thanks you... 11/10
There has clearly been a mistake. Pup did nothing wrong. 12/10 would help escape

Here's a super majestic doggo and a sunset 11/10
This is old now but it's absolutely heckin fantastic and I can't not share it with you all. 13/10
This is a taco. We only rate dogs. Please only send in dogs. Dogs are what we rate. Not tacos. Thank you... 10/10
Just in case anyone's having a bad day. 12/10 would bounce with
Here are two lil cuddly puppers. Both 12/10 would snug like so much
Happy Easter from the squad! 🐇🐶 13/10 for all
I know we only rate dogs, but since it's Easter I guess we could rate a bunny for a change. 10/10 petable as hell
Happy Saturday here's 9 puppers on a bench. 99/90 good work everybody
Here we see an extremely rare Bearded Floofmallow. Only a few left in the wild. 11/10 would pet with a purpose
Please don't send in any more polar bears. We only rate dogs. Thank you... 10/10
Reminder that we made our first set of stickers available! All are 12/10 would stick
Use code "pupper" at checkout🐶


I can't even comprehend how confused this dog must be right now. 10/10
I want to hear the joke this dog was just told. 10/10
Oh. My. God. 13/10 magical af
"Please, no puparazzi" 11/10
What hooligan sent in pictures w/out a dog in them? Churlish af. 3/10 just bc that's a neat fluffy bean bag chair
Here's a brigade of puppers. All look very prepared for whatever happens next. 80/80
I've watched this a million times and you probably will too. 12/10 (vid by @emily_galasso)
We 👏🏻 only 👏🏻 rate 👏🏻 dogs. Pls stop sending in non-canines like this Dutch Panda Worm. This is infuriating. 11/10
The squad is back for St. Patrick's Day! ☘ 💚
13/10 for all
This pupper got her hair chalked for her birthday. Hasn't told her parents yet. Rebellious af. 11/10 very nifty
WeRateDogs stickers are here and they're 12/10! Use code "puppers" at checkout 🐶🐾

Shop now:
*lets out a tiny whimper and then collapses* ...12/10
From left to right:
Cletus, Jerome, Alejandro, Burp, &amp; Titson
None know where camera is. 45/50 would hug all at once
Here's a pupper with magic eyes. Not wearing a seat belt tho (irresponsible af). Very distracting to driver. 9/10
RT if you are as ready for summer as this pup is 12/10
Please stop sending in non canines like this Guatemalan Twiggle Bunny. We only rate dogs. Only send in dogs... 11/10
Everybody stop what you're doing and watch this video. Frank is stuck in a loop. 13/10 (Vid by @klbmatty)
When your roommate eats your leftover Chili's but you pretend it's no big deal cuz you fat anyway. 10/10 head up pup
He's doing his best. 12/10 very impressive that he got his license in the first place
We usually don't rate marshmallows but this one's having so much fun in the snow. 10/10 (vid by @kylejk24)
"I shall trip the big pupper with leash. Big pupper will never see it coming. I am a genius." Both 11/10
This dog just brutally murdered a snowman. Currently toying with its nutritious remains 9/10 would totally still pet
Ever seen a dog pet another dog? Both 13/10 truly an awe-inspiring scene. (Vid by @mdougherty20)
Here's a sneak peek of me on spring break. 10/10 so many tired pups these days
Please enjoy this pup in a cooler. Permanently ready for someone to throw a tennis ball his way. 12/10
Here's a very sleepy pupper. Thinks it's an airplane. 12/10 would snug for eternity
When you're just relaxin and having a swell time but then remember you have to fill out the FAFSA ...11/10
He was doing his best. 12/10 I'll be his lawyer

Seriously, add us 🐶 11/10 for sad wet pupper
"Ma'am, for the last time, I'm not authorized to make that type of transaction" 11/10
I found a forest Pipsy. 12/10
Here is a heartbreaking scene of an incredible pupper being laid to rest. 10/10 RIP pupper
"Yes hi could I get a number 4 with no pickles" ...12/10
This pupper killed this great white in an epic sea battle. Now wears it as a trophy. Such brave. Much fierce. 13/10
When you wake up from a long nap and have no idea who you are. 12/10
This sneezy pupper is just adorable af. 12/10 (vid by @gwilks1)
Here is a whole flock of puppers.  60/50 I'll take the lot
"YOU CAN'T HANDLE THE TRUTH" both 10/10
When you're trying to watch your favorite tv show but your friends keep interrupting. 10/10 relatable af
Really guys? Again? I know this is a rare Albanian Bingo Seal, but we only rate dogs. Only send in dogs... 9/10
This pupper doesn't understand gates. 10/10 so close
Happy Friday here's a sleepy pupper 12/10
This is a Butternut Cumberfloof. It's not windy they just look like that. 11/10 back at it again with the red socks
This is an East African Chalupa Seal. We only rate dogs. Please only send in dogs. Thank you... 10/10
This is a Wild Tuscan Poofwiggle. Careful not to startle. Rare tongue slip. One eye magical. 12/10 would def pet
Please enjoy this picture as much as I did. 12/10
"AND IIIIIIIIIIIEIIIIIIIIIIIII WILL ALWAYS LOVE YOUUUUU" 11/10
I know it's tempting, but please stop sending in pics of Donald Trump. Thank you ...9/10
Please pray for this pupper. Nothing wrong with her she just can't stop getting hit with banana peels. 11/10
I'm not sure what's happening here, but it's pretty spectacular. 12/10 for both
"Pupper is a present to world. Here is a bow for pupper." 12/10 precious as hell
We only rate dogs. Pls stop sending in non-canines like this Mongolian grass snake. This is very frustrating. 11/10
If a pupper gave that to me I'd probably start shaking and faint from all the joy. 11/10
When it's Janet from accounting's birthday but you can't eat the cake cuz it's chocolate. 10/10 hang in there pupper
Take all my money. 10/10
I know this is a tad late but here's a wonderful Valentine's Day pupper 12/10
"Don't ever talk to me or my son again." ...both 10/10
"I'm bathing the children what do you want?"  ...both 10/10
ERMAHGERD 12/10 please enjoy
HAPPY V-DAY FROM YOUR FAV PUPPER SQUAD 13/10 for all
This dog is never sure if he's doing the right thing. 10/10
Here we are witnessing five Guatemalan Birch Floofs in their natural habitat. All 12/10 (Vid by @pootdanielle)
"Dammit hooman quit playin I jus wanna wheat thin" 11/10
Pls make sure ur dogs have gone through some barkour training b4 they attempt stunts like this. 8/10
This pupper doubles as a hallway rug. Very rare. Versatile af. 11/10
Here's a pupper with a piece of pizza. Two of everybody's favorite things in one photo. 11/10
Happy Wednesday here's a bucket of pups. 44/40 would pet all at once
Please stop sending in saber-toothed tigers. This is getting ridiculous. We only rate dogs.
...8/10
These two pirates crashed their ship and don't know what to do now. Very irresponsible of them. Both 9/10
Guys I found the dog from Up. 12/10
12/10 revolutionary af
This poor pupper has been stuck in a vortex since last week. Please keep her in your thoughts. 10/10
Here's a dog enjoying a sunset. 11/10 would trade lives with
If you are aware of who is making these please let me know. 13/10 vroom vroom
We normally don't rate unicorns but this one has 3 ears so it must be super rare. 12/10 majestic af
This is just a beautiful pupper good shit evolution. 12/10
This may be the greatest video I've ever been sent. 4/10 for Charles the puppy, 13/10 overall. (Vid by @stevenxx_)
Please only send in dogs. This t-rex is very scary. 5/10 ...might still pet (vid by @helizabethmicha)
This pupper only appears through the hole of a Funyun. Much like Phineas, this one is also mysterious af. 10/10
It's okay pup. This happens every time I listen to @adele also. 11/10 (vid by @_larirutschmann)
"Martha come take a look at this. I'm so fed up with the media's unrealistic portrayal of dogs these days." 10/10
These lil fellas are the best of friends. 12/10 for both. 1 like = 1 friend (vid by @CassieBrookee15)
What kind of person sends in a pic without a dog in it? So churlish. Neat rug tho 7/10
This pupper is afraid of its own feet. 12/10 would comfort
When you keepin the popcorn bucket in your lap and she reach for some... 10/10
I hope you guys enjoy this beautiful snowy pupper as much as I did. 11/10
"Thank you friend that was a swell petting" 11/10 (vid by @MatthewjamesMac)
Please only send in dogs. Don't submit other things like this pic of Kenny Chesney in a bathtub. Thank you. 9/10
"Fuck the system" 10/10
This pupper just descended from heaven. 12/10 can probably fly
"Hello yes could I get one pupper to go please thank you"
Both 13/10
This is a rare Arctic Wubberfloof. Unamused by the happenings. No longer has the appetites. 12/10 would totally hug
These are some pictures of Teddy that further justify his 13/10 rating. Please enjoy
We usually don't rate penguins but this one is in need of a confidence boost after that slide. 10/10
THE BRITISH ARE COMING
THE BRITISH ARE COMING
10/10
When bae says they can't go out but you see them with someone else that same night. 5/10 &amp; 10/10 for heartbroken pup
I present to you... Dog Jesus. 13/10 (he could be sitting on a rock but I doubt it)
Here we see one dog giving a puptalk to another dog. Both are focused af. Left one has powerful feet. 11/10 for both
Happy Saturday here's a dog in a mailbox. 12/10
We've got a doggy down. Requesting backup. 12/10 for both. Please enjoy
This golden is happy to refute the soft mouth egg test. Not a fan of sweeping generalizations. 11/10 #notallpuppers
She thought the sunset was pretty, but I thought she was prettier. 10/10
Stop sending in lobsters. This is the final warning. We only rate dogs. Thank you... 9/10
This pupper can only sleep on shoes. It's a crippling disease. Tearing his family apart. 12/10 I'd totally pet tho
"I'm the only one that ever does anything in this household" 10/10
Here we are witnessing a rare High Stepping Alaskan Floofer. 12/10 dangerously petable (vid by @TheMrsNux)
Happy Wednesday here's a pup wearing a beret. 12/10 please enjoy
Here we see 33 dogs posing for a picture. All get 11/10 for superb cooperation
Downright majestic af 12/10
Someone sent me this without any context and every aspect of it is spectacular. 13/10 please enjoy
We normally don't rate birds but I feel bad cos this one forgot to fly south for the winter. 9/10 just wants a bath
This pupper just wants to say hello. 11/10 would knock down fence for
When you have a ton of work to do but then remember you have tomorrow off. 10/10
When you stumble but recover quickly cause your crush is watching. 12/10
This pupper is sprouting a flower out of her head. 12/10 revolutionary af
Please send dogs. I'm tired of seeing other stuff like this dangerous pirate. We only rate dogs. Thank you... 10/10
13/10 I can't stop watching this (vid by @k8lynwright)
With great pupper comes great responsibility. 12/10
Another magnificent photo. 12/10
"You got any games on your phone" 7/10 for invasive brown Dalmatian pupper
Army of water dogs here. None of them know where they're going. Have no real purpose. Aggressive barks. 5/10 for all
This pupper's New Year's resolution was to become a Hershey's kiss. 11/10 she's super pumped about it
This pupper forgot how to walk. 12/10 happens to all of us (vid by @bbuckley96)
Strange pup here. Easily manipulated. Rather inbred. Sharp for a dog. Appears uncomfortable. 8/10 would still pet
I just love this picture. 12/10 lovely af
This pup's having a nightmare that he forgot to type a paper due first thing in the morning. 12/10 (vid by ...
Heartwarming scene here. Son reuniting w father after coming home from deployment. Very moving. 10/10 for both pups
When bae calls your name from across the room. 12/10 (vid by @christinemcc98)
Your fav crew is back and this time they're embracing cannabis culture. 12/10 for all
This pupper has a magical eye. 11/10 I can't stop looking at it
This is the newly formed pupper a capella group. They're just starting out but I see tons of potential. 8/10 for all
Everybody needs to read this. Jack is our first 14/10. Truly heroic pupper
For the last time, WE. DO. NOT. RATE. BULBASAUR. We only rate dogs. Please only send dogs. Thank you ...9/10
"Tristan do not speak to me with that kind of tone or I will take away the Xbox." 10/10
I would like everyone to appreciate this pup's face as much as I do. 11/10
"Hello yes I'll just get one of each color thanks" 12/10 for all
Here we have a basking dino pupper. Looks powerful. Occasionally shits eggs. Doesn't want the holidays to end. 5/10
This little fella really hates stairs. Prefers bush. 13/10 legendary pupper
"FOR THE LAST TIME I DON'T WANNA PLAY TWISTER ALL THE SPOTS ARE GREY DAMN IT CINDY" ...10/10
This pupper just got his first kiss. 12/10 he's so happy
After watching this video, we've determined that Pippa will be upgraded to a 12/10. Please enjoy
Two sneaky puppers were not initially seen, moving the rating to 143/130. Please forgive us. Thank you
Someone help the girl is being mugged. Several are distracting her while two steal her shoes. Clever puppers 121/110
Gang of fearless hoofed puppers here. Straight savages. Elevated for extra terror. Front one has killed before 6/10s
"Yo Boomer I'm taking a selfie, grab your stick"
"Ok make sure to get this rad hole I just dug in there"

Both 10/10
Heartwarming scene of two pups that want nothing more than to be together. Touching af. Great tongue. Both 11/10

This is the best thing I've ever seen so spread it like wildfire &amp; maybe we'll find the genius who created it. 13/10
Interesting dog here. Very large. Purple. Manifests rainbows. Perfect teeth. No ears. Surprisingly knowledgable 6/10
Super rare dog here. Spiffy mohawk. Sharp mouth. Shits eggs. Cool chariot wheel in background. 6/10 v confident pup
Striped dog here. Having fun playing on back. Sturdy paws. Looks like an organized Dalmatian. 7/10 would still pet
Tfw she says hello from the other side. 9/10
This pup holds the secrets of the universe in his left eye. 12/10
Pack of horned dogs here. Very team-oriented bunch. All have weird laughs. Bond between them strong. 8/10 for all
*struggling to breathe properly* 12/10
This is a Helvetica Listerine named Rufus. This time Rufus will be ready for the UPS guy. He'll never expect it 9/10
Neat pup here. Enjoys lettuce. Long af ears. Short lil legs. Hops surprisingly high for dog. 9/10 still very petable
Me running from commitment. 10/10
Two miniature golden retrievers here. Webbed paws. Don't walk very efficiently. Can't catch a tennis ball. 4/10s
Yea I can't handle this job anymore your dogs are too adorable. 12/10
After so many requests... here you go.

Good dogg. 420/10
Pink dogs here. Unreasonably long necks. Left guy has only 1 leg. Quite nimble. Don't bark tho 4/10s would still pet
Scary dog here. Too many legs. Extra tail. Not soft, let alone fluffy. Won't bark. Moves sideways. Has weapon. 2/10
Can't do better than this lol. 10/10 for the owner
I would do radical things in the name of Dog God. I'd believe every word in that book. 10/10
Two obedient dogs here. Left one has extra leg sticking out of its back. They each get 9/10. Would pet both at once
Flamboyant pup here. Probably poisonous. Won't eat kibble. Doesn't bark. Slow af. Petting doesn't look fun. 1/10
This dude slaps your girl's ass what do you do?
5/10
"To bone or not to bone?"
10/10
*screams for a little bit and then crumples to the floor shaking* 12/10
Honor to rate this dog. Great teeth. Nice horns. Unbelievable posture. Fun to pet. Big enough to ride. 10/10 rad dog
Silly dog here. Wearing bunny ears. Nice long tail. Unique paws. Not crazy soft but will do. Extremely agile. 7/10
This dog can't see its haters. 11/10
Vibrant dog here. Fabulous tail. Only 2 legs tho. Has wings but can barely fly (lame). Rather elusive. 5/10 okay pup
Two unbelievably athletic dogs here. Great form. Perfect execution. 10/10 for both
This is a Deciduous Trimester mix named Spork. Only 1 ear works. No seat belt. Incredibly reckless. 9/10 still cute
Sharp dog here. Introverted. Loves purple. Not fun to pet. Hurts to cuddle with. 6/10 still good dog tho
This is a Rich Mahogany Seltzer named Cherokee. Just got destroyed by a snowball. Isn't very happy about it. 9/10
AT DAWN...
WE RIDE

11/10
This is a Speckled Cauliflower Yosemite named Hemry. He's terrified of intruder dog. Not one bit comfortable. 9/10
"Hi yes this is dog. I can't help with that s- sir please... the manager isn't in right n- well that was rude"
10/10
😂😂😂 10/10 for the dog and the owner
Awesome dog here. Not sure where it is tho. Spectacular camouflage. Enjoys leaves. Not very soft. 5/10 still petable
Here we see really big dog cuddling smaller dog. Very touching. True friendship. 10/10s would pet both at once
I've never seen a dog so genuinely happy about a tennis ball. 12/10 s'cute
This is a spotted Lipitor Rumpelstiltskin named Alphred. He can't wait for the Turkey. 10/10 would pet really well
This is a brave dog. Excellent free climber. Trying to get closer to God. Not very loyal though. Doesn't bark. 5/10
Very human-like. Cute overbite smile *finger to earpiece* I'm being told that the dog is actually on the right
10/10
Special dog here. Pretty big. Neck kinda long for dog. Cool spots. Must be a Dalmatian variant. 6/10 would still pet
This is a Coriander Baton Rouge named Alfredo. Loves to cuddle with smaller well-dressed dog. 10/10 would hug lots
Here we have a Gingivitis Pumpernickel named Zeus. Unmatched tennis ball capacity. 10/10 would highly recommend
Just got home from college. Dis my dog. She does all my homework. Big red turd in background. 13/10 no bias at all
Here we have Pancho and Peaches. Pancho is a Condoleezza Gryffindor, and Peaches is just an asshole. 10/10 &amp; 7/10
Super rare dog right here guys. Doesn't bark. Seems strong. Blue. Very family friendly pet. 10/10 overall good dog
Two gorgeous pups here. Both have cute fake horns(adorable). Barn in the back looks on fire. 5/10 would pet rly well
Honor to rate this dog. Lots of fur on him. Two massive tumors on back. Should get checked out. Very neat tho. 7/10
Unique dog here. Oddly shaped tail. Long pink front legs. I don't think dogs breath underwater sos. 4/10 bad owner
This is a Slovakian Helter Skelter Feta named Leroi. Likes to skip on roofs. Good traction. Much balance. 10/10 wow!
This is a wild Toblerone from Papua New Guinea. Mouth always open. Addicted to hay. Acts blind. 7/10 handsome dog
Incredibly rare dog here. Good at bipedalism. Rad blue spikes. Ready to dance. 11/10
Fascinating dog here. Loves beach. Oddly long nose for dog. Massive ass paws. Hard to cuddle w. 3/10 would still pet
This is an Irish Rigatoni terrier named Berta. Completely made of rope. No eyes. Quite large. Loves to dance. 10/10
Here is a horned dog. Much grace. Can jump over moons (dam!). Paws not soft. Bad at barking. 7/10 can still pet tho
Never forget this vine. You will not stop watching for at least 15 minutes. This is the second coveted.. 13/10
It is an honor to rate this pup. He is a Snorklhuahua from Amarillo. A true renaissance dog. Also part Rudolph 10/10
There's a lot going on here but in my honest opinion every dog pictured is pretty fabulous. 10/10 for all. Good dogs
This is a Birmingham Quagmire named Chuk. Loves to relax and watch the game while sippin on that iced mocha. 10/10
Good teamwork between these dogs. One is on lookout while other eats. Long necks. Nice big house. 9/10s good pups
Here is a mother dog caring for her pups. Snazzy red mohawk. Doesn't wag tail. Pups look confused. Overall 4/10
2 rare dogs. They waddle (v inefficient). Sometimes slide on bellies. Right one wants to be aircraft Marshall. 9/10s
I can't do better than he did. 10/10
Here we have an Azerbaijani Buttermilk named Guss. He sees a demon baby Hitler behind his owner. 10/10 stays alert
Sneaky dog here. Tuba player has no clue. 10/10 super sneaky
These two dogs are Bo &amp; Smittens. Smittens is trying out a new deodorant and wanted Bo to smell it. 10/10 true pals
This is a Trans Siberian Kellogg named Alfonso. Huge ass eyeballs. Actually Dobby from Harry Potter. 7/10
Fun dogs here. Top one clearly an athlete. Bottom one very stable. Not very soft tho. 9/10s would still cuddle both
This lil pup is Oliver. Hops around. Has wings but doesn't fly (lame). Annoying chirp. Won't catch tennis balls 2/10
This dog resembles a baked potato. Bed looks uncomfortable. No tail. Comes with butter tho. 3/10 petting still fun
Wow. Armored dog here. Ready for battle. Face looks dangerous. Not very loyal. Lil dog on back havin a blast. 5/10
Neat dog. Lots of spikes. Always in push-up position. Laid a shit ton of eggs earlier. Super stellar pup. 10/10
This is a Shotokon Macadamia mix named Cheryl. Sophisticated af. Looks like a disappointed librarian. Shh (lol) 9/10
THE EYES 12/10

I'm sorry. These are supposed to be funny but your dogs are too adorable
OMIGOD 12/10
Dogs only please. Small cows and other non canines will not be tolerated. Sick tattoos tho 8/10
Super rare dog. Endangered (?). Thinks it's funny. Mocks everything I say. Colorful af. Has wings (dope). 9/10
This is a rare Hungarian Pinot named Jessiga. She is either mid-stroke or got stuck in the washing machine. 8/10
What a dog to start the day with. Very calm. Likes to chill by pond. Corkscrews sticking out of head. Obedient. 7/10
Never seen dog like this. Breathes heavy. Tilts head in a pattern. No bark. Shitty at fetch. Not even cordless. 1/10
This is a southwest Coriander named Klint. Hat looks expensive. Still on house arrest :(
9/10
Another topnotch dog. His name is Big Jumpy Rat. Massive ass feet. Superior tail. Jumps high af. 12/10 great pup
This a Norwegian Pewterschmidt named Tickles. Ears for days. 12/10 I care deeply for Tickles
Two dogs in this one. Both are rare Jujitsu Pythagoreans. One slightly whiter than other. Long legs. 7/10 and 8/10
This is a northern Wahoo named Kohl. He runs this town. Chases tumbleweeds. Draws gun wicked fast. 11/10 legendary
Exotic dog here. Long neck. Weird paws. Obsessed with bread. Waddles. Flies sometimes (wow!). Very happy dog. 6/10
Never seen this breed before. Very pointy pup. Hurts when you cuddle. Still cute tho. 10/10
Ermergerd 12/10
Here we have a neat pup. Very white. Cool shades. Upcoming cruise? Great dog 10/10
*takes several long deep breaths* omg omg oMG OMG OMG OMGSJYBSNDUYWJO 12/10
Quite an advanced dog here. Impressively dressed for canine. Has weapon. About to take out trash. 10/10 good dog
This is a Dasani Kingfisher from Maine. His name is Daryl. Daryl doesn't like being swallowed by a panda. 8/10
These are strange dogs. All have toupees. Long neck for dogs. In a shed of sorts? Work in groups? 4/10 still petable
Extremely intelligent dog here. Has learned to walk like human. Even has his own dog. Very impressive 10/10
Here we have a Hufflepuff. Loves vest. Eyes wide af. Flaccid tail. Matches carpet. Always a little blurry. 8/10
12/10 gimme now
This is a curly Ticonderoga named Pepe. No feet. Loves to jet ski. 11/10 would hug until forever
My goodness. Very rare dog here. Large. Tail dangerous. Kinda fat. Only eats leaves. Doesn't come when called 3/10
These are Peruvian Feldspars. Their names are Cupit and Prencer. Both resemble Rand Paul. Sick outfits 10/10 &amp; 10/10
12/10 simply brilliant pup
Unfamiliar with this breed. Ears pointy af. Won't let go of seashell. Won't eat kibble. Not very fast. Bad dog 2/10
This is a purebred Bacardi named Octaviath. Can shoot spaghetti out of mouth. 10/10
This is a golden Buckminsterfullerene named Johm. Drives trucks. Lumberjack (?). Enjoys wall. 8/10 would hug softly
Cool dog. Enjoys couch. Low monotone bark. Very nice kicks. Pisses milk (must be rare). Can't go down stairs. 4/10
Here we see a lone northeastern Cumberbatch. Half ladybug. Only builds with bricks. Very confident with body. 7/10
"Can you behave? You're ruining my wedding day"
DOG: idgaf this flashlight tastes good as hell

10/10
Oh boy what a pup! Sunglasses take this one to the next level. Weirdly folds front legs. Pretty big. 6/10
Here we have an Austrian Pulitzer. Collectors edition. Levitates (?). 7/10 would garden with
*internally screaming* 12/10
This is quite the dog. Gets really excited when not in water. Not very soft tho. Bad at fetch. Can't do tricks. 2/10
This is a southern Vesuvius bumblegruff. Can drive a truck (wow). Made friends with 5 other nifty dogs (neat). 7/10
Oh goodness. A super rare northeast Qdoba kangaroo mix. Massive feet. No pouch (disappointing). Seems alert. 9/10
Those are sunglasses and a jean jacket. 11/10 dog cool af
Unique dog here. Very small. Lives in container of Frosted Flakes (?). Short legs. Must be rare 6/10 would still pet
Here we have a mixed Asiago from the Galápagos Islands. Only one ear working. Big fan of marijuana carpet. 8/10
Look at this jokester thinking seat belt laws don't apply to him. Great tongue tho 10/10
This is an extremely rare horned Parthenon. Not amused. Wears shoes. Overall very nice. 9/10 would pet aggressively
This is a funny dog. Weird toes. Won't come down. Loves branch. Refuses to eat his food. Hard to cuddle with. 3/10
This is an Albanian 3 1/2 legged  Episcopalian. Loves well-polished hardwood flooring. Penis on the collar. 9/10
Can take selfies 11/10
Very concerned about fellow dog trapped in computer. 10/10
Not familiar with this breed. No tail (weird). Only 2 legs. Doesn't bark. Surprisingly quick. Shits eggs. 1/10
Oh my. Here you are seeing an Adobe Setter giving birth to twins!!! The world is an amazing place. 11/10
Can stand on stump for what seems like a while. Built that birdhouse? Impressive. Made friends with a squirrel. 8/10
This appears to be a Mongolian Presbyterian mix. Very tired. Tongue slip confirmed. 9/10 would lie down with
Here we have a well-established sunblockerspaniel. Lost his other flip-flop. 6/10 not very waterproof
Let's hope this flight isn't Malaysian (lol). What a dog! Almost completely camouflaged. 10/10 I trust this pilot
Here we have a northern speckled Rhododendron. Much sass. Gives 0 fucks. Good tongue. 9/10 would caress sensually
This is the happiest dog you will ever see. Very committed owner. Nice couch. 10/10
Here is the Rand Paul of retrievers folks! He's probably good at poker. Can drink beer (lol rad). 8/10 good dog
My oh my. This is a rare blond Canadian terrier on wheels. Only $8.98. Rather docile. 9/10 very rare
Here is a Siberian heavily armored polar bear mix. Strong owner. 10/10 I would do unspeakable things to pet this dog
This is an odd dog. Hard on the outside but loving on the inside. Petting still fun. Doesn't play catch well. 2/10
This is a truly beautiful English Wilson Staff retriever. Has a nice phone. Privileged. 10/10 would trade lives with
Here we have a 1949 1st generation vulpix. Enjoys sweat tea and Fox News. Cannot be phased. 5/10
This is a purebred Piers Morgan. Loves to Netflix and chill. Always looks like he forgot to unplug the iron. 6/10
Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would cuddle af
This is a western brown Mitsubishi terrier. Upset about leaf. Actually 2 dogs here. 7/10 would walk the shit out of

In [45]:
#Count of name column values with NaN
print(len(dogsTwitter_archive.name[dogsTwitter_archive.name.isnull()]))

726

In [46]:
for index in range(len(dogsTwitter_archive)):
    if dogsTwitter_archive['name'].isnull().iloc[index]:
        if len(dogsTwitter_archive['text'].str.findall('name is\s(\w+)').iloc[index]) > 0:
            dogsTwitter_archive['name'].iloc[index] = dogsTwitter_archive['text'].str.findall('name is\s(\w+)').iloc[index]
        elif len(dogsTwitter_archive['text'].str.findall('named\s(\w+)\s').iloc[index]) > 0:
            dogsTwitter_archive['name'].iloc[index] = dogsTwitter_archive['text'].str.findall('named\s(\w+)\s').iloc[index]

In [47]:
#One of the records with None as names. There is actually no name even in the text
print(dogsTwitter_archive['text'][2353])
print(dogsTwitter_archive['name'][2353])

# I can still see 'text' column truncation but that seems to be how it is written in 'full_text' also and hence not an error.

Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would cuddle af
nan

#### Test

In [48]:
#Inspecting the names in the 'name' column
print(dogsTwitter_archive.name.values)

['Phineas' 'Tilly' 'Archie' ..., nan nan "O'Malley"]

In [49]:
print(len(dogsTwitter_archive.name[dogsTwitter_archive.name.isnull()]))
# Now we have only 718 null values. 
# Also 'non_dog' names which were populated in the 'name' column like 'a', 'an' etc have been replaced by 'None'

718

#### Define

5.. Unusual values for rating_numerator and rating_denominator columns. Find the unsual values and fix them if required.

#### Code

In [50]:
dogsTwitter_archive
dogsTwitter_archive['tweet_id'].value_counts()

749075273010798592    1
685315239903100929    1
715696743237730304    1
691820333922455552    1
776477788987613185    1
760521673607086080    1
880095782870896641    1
699775878809702401    1
780858289093574656    1
700462010979500032    1
769212283578875904    1
738883359779196928    1
743510151680958465    1
833722901757046785    1
805487436403003392    1
842765311967449089    1
673686845050527744    1
667073648344346624    1
666051853826850816    1
809920764300447744    1
818259473185828864    1
759923798737051648    1
670093938074779648    1
672082170312290304    1
667160273090932737    1
756651752796094464    1
743545585370791937    1
671163268581498880    1
770655142660169732    1
793120401413079041    1
                     ..
825026590719483904    1
834209720923721728    1
775733305207554048    1
669564461267722241    1
879492040517615616    1
720775346191278080    1
870308999962521604    1
872261713294495745    1
693155686491000832    1
667911425562669056    1
740373189193256964    1
754482103782404096    1
673342308415348736    1
794926597468000259    1
666817836334096384    1
715360349751484417    1
748307329658011649    1
671735591348891648    1
669970042633789440    1
767500508068192258    1
837482249356513284    1
674291837063053312    1
683773439333797890    1
713175907180089344    1
670338931251150849    1
843604394117681152    1
770772759874076672    1
675898130735476737    1
791672322847637504    1
700151421916807169    1
Name: tweet_id, Length: 2117, dtype: int64

In [51]:
dogsTwitter_archive[['text', 'rating_numerator', 'rating_denominator', 'source']][dogsTwitter_archive['rating_numerator'] > 20].values

array([[ 'The floofs have been released I repeat the floofs have been released. 84/70 ',
        84, 70, list(['Twitter for iPhone'])],
       [ 'Meet Sam. She smiles 24/7 &amp; secretly aspires to be a reindeer. \nKeep Sam smiling by clicking and sharing this link:\n',
        24, 7, list(['Twitter for iPhone'])],
       [ "This is Logan, the Chow who lived. He solemnly swears he's up to lots of good. H*ckin magical af 9.75/10 ",
        75, 10, list(['Twitter for iPhone'])],
       [ "This is Sophie. She's a Jubilant Bush Pupper. Super h*ckin rare. Appears at random just to smile at the locals. 11.27/10 would smile back ",
        27, 10, list(['Twitter for iPhone'])],
       ['Why does this never happen at my front door... 165/150 ', 165,
        150, list(['Twitter for iPhone'])],
       ["This is Atticus. He's quite simply America af. 1776/10 ", 1776,
        10, list(['TweetDeck'])],
       [ 'Say hello to this unbelievably well behaved squad of doggos. 204/170 would try to pet all at once ',
        204, 170, list(['Twitter for iPhone'])],
       [ 'This is Bluebert. He just saw that both #FinalFur match ups are split 50/50. Amazed af. 11/10 ',
        50, 50, list(['Twitter for iPhone'])],
       ["Happy Saturday here's 9 puppers on a bench. 99/90 good work everybody ",
        99, 90, list(['Twitter for iPhone'])],
       [ "Here's a brigade of puppers. All look very prepared for whatever happens next. 80/80 ",
        80, 80, list(['Twitter for iPhone'])],
       [ 'From left to right:\nCletus, Jerome, Alejandro, Burp, &amp; Titson\nNone know where camera is. 45/50 would hug all at once ',
        45, 50, list(['Twitter for iPhone'])],
       ["Here is a whole flock of puppers.  60/50 I'll take the lot ", 60,
        50, list(['Twitter for iPhone'])],
       ["Happy Wednesday here's a bucket of pups. 44/40 would pet all at once ",
        44, 40, list(['Twitter for iPhone'])],
       [ 'Two sneaky puppers were not initially seen, moving the rating to 143/130. Please forgive us. Thank you ',
        143, 130, list(['Twitter for iPhone'])],
       [ 'Someone help the girl is being mugged. Several are distracting her while two steal her shoes. Clever puppers 121/110 ',
        121, 110, list(['Twitter for iPhone'])],
       [ 'Here we have uncovered an entire battalion of holiday puppers. Average of 11.26/10 ',
        26, 10, list(['Twitter for iPhone'])],
       ["IT'S PUPPERGEDDON. Total of 144/120 ...I think ", 144, 120,
        list(['Twitter for iPhone'])],
       [ 'Here we have an entire platoon of puppers. Total score: 88/80 would pet all at once ',
        88, 80, list(['Twitter for iPhone'])],
       ['After so many requests... here you go.\n\nGood dogg. 420/10 ',
        420, 10, list(['Twitter for iPhone'])]], dtype=object)

I expected the extremely high rating to be some data error but it seems like most of the high ratings, esp, 1776/10 are valid.

The erros are in places where there are multiple ratings in text. in such cases, the first rating (sometimes invalid like 666/00) seems to be taken instead of actual rating. This needs to be corrected.

In [52]:
# Only the last ratio in the text would be the actual ratio. The last ratio needs to be extracted out and used for populating the rating columns
ratings = dogsTwitter_archive['text'].str.findall('(\d+)/(\d+)')
dogsTwitter_archive['ratings'] = ratings

#Random check
len(dogsTwitter_archive['ratings'][2335])
print(dogsTwitter_archive['ratings'][2335])   # Has two elements - [('1', '2'), ('9', '10')]
print(len(dogsTwitter_archive.ratings.iloc[27]))
print(dogsTwitter_archive.text.iloc[27])
print(dogsTwitter_archive['text'].str.findall('(\d+)/(\d+)')[27])
index = 27
print(dogsTwitter_archive.loc[27, 'ratings'])
print(dogsTwitter_archive.ratings.iloc[114])

[('1', '2'), ('9', '10')]
1
This is Derek. He's late for a dog meeting. 13/10 pet...al to the metal
[('13', '10')]
[('13', '10')]
[('12', '10')]

In [53]:
# Not used
#The above code won't catch ratings which ends with a . or ,.
# Hence, if the rating column length is 0 after the above step, run the below code to check again   
#condition = (dogsTwitter_archive.ratings.str.len() == 0)
#dogsTwitter_archive.loc[condition, 'ratings'] = dogsTwitter_archive['text'].str.findall('(\d+)/(\d+)')

In [54]:
#Test
print(dogsTwitter_archive.loc[27, 'ratings'])
#print(dogsTwitter_archive.ratings)
print(dogsTwitter_archive['ratings'].iloc[114])

[('13', '10')]
[('12', '10')]

In [55]:
# Looping through the new 'ratings' column, if there are more than one element in the ratings list, consider the last one as rating
for index in range(len(dogsTwitter_archive)):
    try:
        if len(dogsTwitter_archive['ratings'].iloc[index]) > 1:
            value_tuple = dogsTwitter_archive['ratings'].iloc[index].pop()  #extracting the right rating
            dogsTwitter_archive['ratings'].iloc[index] = [(value_tuple)]     #setting the original cell to list before appending
            #dogsTwitter_archive['ratings'].iloc[index].append(value_tuple) 
    except:
        print(index, "has possible null values")
# Ignoring the warning

In [56]:
print(dogsTwitter_archive.iloc[2036])

tweet_id                                             667455448082227200
timestamp                                     2015-11-19 21:32:34 +0000
source                                             [Twitter Web Client]
text                  This is Reese and Twips. Reese protects Twips....
expanded_urls         https://twitter.com/dog_rates/status/667455448...
rating_numerator                                                      7
rating_denominator                                                   10
name                                                              Reese
doggo                                                              None
floofer                                                            None
pupper                                                             None
puppo                                                              None
ratings                                                       [(7, 10)]
Name: 2274, dtype: object

In [57]:
#Visually inspecting if the extracted ratings are correct if there is a difference in the current ratings_numerator and ratings
for index in range(len(dogsTwitter_archive)):
    if (dogsTwitter_archive['ratings'].isnull().iloc[index]):  
        print(dogsTwitter_archive.iloc[index].values, "\n")
    elif (int(dogsTwitter_archive['rating_numerator'].iloc[index]) == int(dogsTwitter_archive['ratings'].iloc[index][0][0])):
        continue
    else:
        print(dogsTwitter_archive.iloc[index].values, "\n")

[777684233540206592 '2016-09-19 01:42:24 +0000'
 list(['Twitter for iPhone'])
 '"Yep... just as I suspected. You\'re not flossing." 12/10 and 11/10 for the pup not flossing '
 'https://twitter.com/dog_rates/status/777684233540206592/photo/1' 12 10
 nan 'None' 'None' 'None' 'None' list([('11', '10')])]

[747600769478692864 '2016-06-28 01:21:27 +0000'
 list(['Twitter for iPhone'])
 'This is Bookstore and Seaweed. Bookstore is tired and Seaweed is an asshole. 10/10 and 7/10 respectively '
 'https://twitter.com/dog_rates/status/747600769478692864/photo/1,https://twitter.com/dog_rates/status/747600769478692864/photo/1'
 10 10 'Bookstore' 'None' 'None' 'None' 'None' list([('7', '10')])]

[740373189193256964 '2016-06-08 02:41:38 +0000'
 list(['Twitter for iPhone'])
 'After so many requests, this is Bretagne. She was the last surviving 9/11 search dog, and our second ever 14/10. RIP '
 'https://twitter.com/dog_rates/status/740373189193256964/photo/1,https://twitter.com/dog_rates/status/740373189193256964/photo/1,https://twitter.com/dog_rates/status/740373189193256964/photo/1,https://twitter.com/dog_rates/status/740373189193256964/photo/1'
 9 11 nan 'None' 'None' 'None' 'None' list([('14', '10')])]

[722974582966214656 '2016-04-21 02:25:47 +0000'
 list(['Twitter for iPhone']) 'Happy 4/20 from the squad! 13/10 for all '
 'https://twitter.com/dog_rates/status/722974582966214656/photo/1' 4 20 nan
 'None' 'None' 'None' 'None' list([('13', '10')])]

[716439118184652801 '2016-04-03 01:36:11 +0000'
 list(['Twitter for iPhone'])
 'This is Bluebert. He just saw that both #FinalFur match ups are split 50/50. Amazed af. 11/10 '
 'https://twitter.com/dog_rates/status/716439118184652801/photo/1' 50 50
 'Bluebert' 'None' 'None' 'None' 'None' list([('11', '10')])]

[714258258790387713 '2016-03-28 01:10:13 +0000'
 list(['Twitter for iPhone'])
 "Meet Travis and Flurp. Travis is pretty chill but Flurp can't lie down properly. 10/10 &amp; 8/10\nget it together Flurp "
 'https://twitter.com/dog_rates/status/714258258790387713/photo/1' 10 10
 'Travis' 'None' 'None' 'None' 'None' list([('8', '10')])]

[703356393781329922 '2016-02-26 23:10:06 +0000'
 list(['Twitter for iPhone'])
 'This is Socks. That water pup w the super legs just splashed him. Socks did not appreciate that. 9/10 and 2/10 '
 'https://twitter.com/dog_rates/status/703356393781329922/photo/1' 9 10
 'Socks' 'None' 'None' 'None' 'None' list([('2', '10')])]

[695064344191721472 '2016-02-04 02:00:27 +0000'
 list(['Twitter for iPhone'])
 "This may be the greatest video I've ever been sent. 4/10 for Charles the puppy, 13/10 overall. (Vid by @stevenxx_) "
 'https://twitter.com/dog_rates/status/695064344191721472/video/1' 4 10 nan
 'None' 'None' 'None' 'None' list([('13', '10')])]

[694352839993344000 '2016-02-02 02:53:12 +0000'
 list(['Twitter for iPhone'])
 "Meet Oliviér. He takes killer selfies. Has a dog of his own. It leaps at random &amp; can't bark for shit. 10/10 &amp; 5/10 "
 'https://twitter.com/dog_rates/status/694352839993344000/photo/1,https://twitter.com/dog_rates/status/694352839993344000/photo/1,https://twitter.com/dog_rates/status/694352839993344000/photo/1,https://twitter.com/dog_rates/status/694352839993344000/photo/1'
 10 10 'Oliviér' 'None' 'None' 'None' 'None' list([('5', '10')])]

[691483041324204033 '2016-01-25 04:49:38 +0000'
 list(['Twitter for iPhone'])
 "When bae says they can't go out but you see them with someone else that same night. 5/10 &amp; 10/10 for heartbroken pup "
 'https://twitter.com/dog_rates/status/691483041324204033/photo/1,https://twitter.com/dog_rates/status/691483041324204033/photo/1,https://twitter.com/dog_rates/status/691483041324204033/photo/1,https://twitter.com/dog_rates/status/691483041324204033/photo/1'
 5 10 nan 'None' 'None' 'None' 'None' list([('10', '10')])]

[690400367696297985 '2016-01-22 05:07:29 +0000'
 list(['Twitter for iPhone'])
 "This is Eriq. His friend just reminded him of last year's super bowl. Not cool friend\n10/10 for Eriq\n6/10 for friend "
 'https://twitter.com/dog_rates/status/690400367696297985/photo/1' 10 10
 'Eriq' 'None' 'None' 'None' 'None' list([('6', '10')])]

[689835978131935233 '2016-01-20 15:44:48 +0000'
 list(['Twitter for iPhone'])
 'Meet Fynn &amp; Taco. Fynn is an all-powerful leaf lord and Taco is in the wrong place at the wrong time. 11/10 &amp; 10/10 '
 'https://twitter.com/dog_rates/status/689835978131935233/photo/1' 11 10
 'Fynn' 'None' 'None' 'None' 'None' list([('10', '10')])]

[682962037429899265 '2016-01-01 16:30:13 +0000'
 list(['Twitter for iPhone'])
 'This is Darrel. He just robbed a 7/11 and is in a high speed police chase. Was just spotted by the helicopter 10/10 '
 'https://twitter.com/dog_rates/status/682962037429899265/photo/1' 7 11
 'Darrel' 'None' 'None' 'None' 'None' list([('10', '10')])]

[677314812125323265 '2015-12-17 02:30:09 +0000'
 list(['Twitter for iPhone'])
 'Meet Tassy &amp; Bee. Tassy is pretty chill, but Bee is convinced the Ruffles are haunted. 10/10 &amp; 11/10 respectively '
 'https://twitter.com/dog_rates/status/677314812125323265/photo/1,https://twitter.com/dog_rates/status/677314812125323265/photo/1'
 10 10 'Tassy' 'None' 'None' 'None' 'None' list([('11', '10')])]

[676191832485810177 '2015-12-14 00:07:50 +0000'
 list(['Twitter for iPhone'])
 'These two pups just met and have instantly bonded. Spectacular scene. Mesmerizing af. 10/10 and 7/10 for blue dog '
 'https://twitter.com/dog_rates/status/676191832485810177/photo/1,https://twitter.com/dog_rates/status/676191832485810177/photo/1,https://twitter.com/dog_rates/status/676191832485810177/photo/1'
 10 10 nan 'None' 'None' 'None' 'None' list([('7', '10')])]

[674737130913071104 '2015-12-09 23:47:22 +0000'
 list(['Twitter for iPhone'])
 'Meet Rufio. He is unaware of the pink legless pupper wrapped around him. Might want to get that checked 10/10 &amp; 4/10 '
 'https://twitter.com/dog_rates/status/674737130913071104/photo/1' 10 10
 'Rufio' 'None' 'None' 'pupper' 'None' list([('4', '10')])]

[674646392044941312 '2015-12-09 17:46:48 +0000'
 list(['Twitter for iPhone'])
 'Two gorgeous dogs here. Little waddling dog is a rebel. Refuses to look at camera. Must be a preteen. 5/10 &amp; 8/10 '
 'https://twitter.com/dog_rates/status/674646392044941312/photo/1' 5 10 nan
 'None' 'None' 'None' 'None' list([('8', '10')])]

[673295268553605120 '2015-12-06 00:17:55 +0000'
 list(['Twitter for iPhone'])
 "Meet Eve. She's a raging alcoholic 8/10 (would b 11/10 but pupper alcoholism is a tragic issue that I can't condone) "
 'https://twitter.com/dog_rates/status/673295268553605120/photo/1' 8 10
 'Eve' 'None' 'None' 'pupper' 'None' list([('11', '10')])]

[672248013293752320 '2015-12-03 02:56:30 +0000'
 list(['Twitter for iPhone'])
 '10/10 for dog. 7/10 for cat. 12/10 for human. Much skill. Would pet all '
 'https://twitter.com/dog_rates/status/672248013293752320/photo/1' 10 10
 nan 'None' 'None' 'None' 'None' list([('12', '10')])]

[671154572044468225 '2015-11-30 02:31:34 +0000'
 list(['Twitter for iPhone'])
 "Meet Holly. She's trying to teach small human-like pup about blocks but he's not paying attention smh. 11/10 &amp; 8/10 "
 'https://twitter.com/dog_rates/status/671154572044468225/photo/1' 11 10
 'Holly' 'None' 'None' 'None' 'None' list([('8', '10')])]

[670434127938719744 '2015-11-28 02:48:46 +0000'
 list(['Twitter for iPhone'])
 "Meet Hank and Sully. Hank is very proud of the pumpkin they found and Sully doesn't give a shit. 11/10 and 8/10 "
 'https://twitter.com/dog_rates/status/670434127938719744/photo/1' 11 10
 'Hank' 'None' 'None' 'None' 'None' list([('8', '10')])]

[669037058363662336 '2015-11-24 06:17:19 +0000'
 list(['Twitter for iPhone'])
 'Here we have Pancho and Peaches. Pancho is a Condoleezza Gryffindor, and Peaches is just an asshole. 10/10 &amp; 7/10 '
 'https://twitter.com/dog_rates/status/669037058363662336/photo/1' 10 10
 nan 'None' 'None' 'None' 'None' list([('7', '10')])]

[668537837512433665 '2015-11-22 21:13:35 +0000'
 list(['Twitter for iPhone'])
 "This is Spark. He's nervous. Other dog hasn't moved in a while. Won't come when called. Doesn't fetch well 8/10&amp;1/10 "
 'https://twitter.com/dog_rates/status/668537837512433665/photo/1' 8 10
 'Spark' 'None' 'None' 'None' 'None' list([('1', '10')])]

[667544320556335104 '2015-11-20 03:25:43 +0000'
 list(['Twitter Web Client'])
 'This is Kial. Kial is either wearing a cape, which would be rad, or flashing us, which would be rude. 10/10 or 4/10 '
 'https://twitter.com/dog_rates/status/667544320556335104/photo/1' 10 10
 'Kial' 'None' 'None' 'None' 'None' list([('4', '10')])]

[667491009379606528 '2015-11-19 23:53:52 +0000'
 list(['Twitter Web Client'])
 'Two dogs in this one. Both are rare Jujitsu Pythagoreans. One slightly whiter than other. Long legs. 7/10 and 8/10 '
 'https://twitter.com/dog_rates/status/667491009379606528/photo/1' 7 10 nan
 'None' 'None' 'None' 'None' list([('8', '10')])]

[666287406224695296 '2015-11-16 16:11:11 +0000'
 list(['Twitter for iPhone'])
 'This is an Albanian 3 1/2 legged  Episcopalian. Loves well-polished hardwood flooring. Penis on the collar. 9/10 '
 'https://twitter.com/dog_rates/status/666287406224695296/photo/1' 1 2 nan
 'None' 'None' 'None' 'None' list([('9', '10')])]

Most of the images with more than two dogs has varying ratios [existing and extracted]. I am going to keep the higher one.  
During visual inspection I found that there is a ratio 50/50 to mean 50-50 and not a rating but was incorrectly extracted. To prevent replacement of such correct records, I am going to compare with the denominator also and replace only if the denominator remains the same but the numerator value is higher.

In [58]:
# Compare numerator and denominator ratings with extracted ratings.  
# Replace rating column value if denominator remains the same but numerator is higher.  
for index in range(len(dogsTwitter_archive)):
    if (int(dogsTwitter_archive['rating_numerator'].iloc[index]) == int(dogsTwitter_archive['ratings'].iloc[index][0][0])):
        continue
    else:
        # denominator is same
        if (int(dogsTwitter_archive['rating_denominator'].iloc[index]) == int(dogsTwitter_archive['ratings'].iloc[index][0][1])):
            # numerator is greater
            if (int(dogsTwitter_archive['rating_numerator'].iloc[index]) > int(dogsTwitter_archive['ratings'].iloc[index][0][0])):
                dogsTwitter_archive['ratings'].iloc[index] = [(dogsTwitter_archive['rating_numerator'].iloc[index], dogsTwitter_archive['rating_denominator'].iloc[index])] 
                print(dogsTwitter_archive['ratings'].iloc[index], "\n")

[(12, 10)]

[(10, 10)]

[(10, 10)]

[(9, 10)]

[(10, 10)]

[(10, 10)]

[(11, 10)]

[(10, 10)]

[(10, 10)]

[(11, 10)]

[(11, 10)]

[(10, 10)]

[(8, 10)]

[(10, 10)]

In [59]:
# Test to see if extracted properly
print(int(dogsTwitter_archive['ratings'].iloc[55][0][0]))
dogsTwitter_archive['rating_numerator'].iloc[55]
print(dogsTwitter_archive['text'].iloc[55])

#Rating extracted properly

12
This is Bella. She had her first beach experience this morning. Complete success. 12/10 would perform a sandy boop

In [60]:
dogsTwitter_archive.ratings.iloc[114]

[('12', '10')]

In [61]:
# Now extract the values of rating column to populate in rating_numerator and rating_denominator
# Then remove the ratings column
for index in range(len(dogsTwitter_archive)):
    # replace rating_numerator
    dogsTwitter_archive['rating_numerator'].iloc[index] = int(dogsTwitter_archive['ratings'].iloc[index][0][0])
    # replace rating_numerator
    dogsTwitter_archive['rating_denominator'].iloc[index] = int(dogsTwitter_archive['ratings'].iloc[index][0][1])
    
# Ignoring the warning

#### Test

In [62]:
#Random testing
dogsTwitter_archive['ratings'][2335]
# Now this has only one element (a tuple inside list as needed)

[('9', '10')]

In [63]:
# Test to see if any element in the rating has more than 1 element
for index in range(len(dogsTwitter_archive)):
    if len(dogsTwitter_archive['ratings'].iloc[index]) <= 1:
        continue
    else:
        print("Not fully cleaned", index)
        
# Hence all elements now only has one rating.

In [64]:
(dogsTwitter_archive['rating_numerator'].iloc[590])

12

In [65]:
print([(2,3)])

[(2, 3)]

In [66]:
# checking for null/nan values
print(dogsTwitter_archive['ratings'].isnull().sum())
print(dogsTwitter_archive['rating_denominator'].isnull().sum())
print(dogsTwitter_archive['rating_numerator'].isnull().sum())

0
0
0

In [67]:
# Testing if any rating_numerator or rating_denominator value is 0 or nan or null
for index in range(len(dogsTwitter_archive)):
    # test denominator for zero values
    if (dogsTwitter_archive['rating_denominator'].iloc[index] == 0):
        print("Error for rating_numerator for tweet at index: ", index)
# no zero values in denominator
# Hence the columns seems to be clean.

# now I can drop the ratings column
dogsTwitter_archive.drop('ratings', axis=1, inplace=True)
dogsTwitter_archive.columns.values

array(['tweet_id', 'timestamp', 'source', 'text', 'expanded_urls',
       'rating_numerator', 'rating_denominator', 'name', 'doggo',
       'floofer', 'pupper', 'puppo'], dtype=object)

#### Define

6.. Convert columns to appropriate datatypes for easier analysis:  
        i. tweet_id, in_reply_to_status_id, in_reply_to_user_id, retweeted_status_id, retweeted_status_user_id columns should be categories (i prefer it to be categories rather than strings)   
        ii. retweeted_status_timestamp column should be datetime format. 

**Since reply related and retweet related columns were removed in the above clean step, only tweet_id dtype needs to be changed now.**

#### Code

In [68]:
#Converting to appropriate dtypes
# converting to categorical data
dogsTwitter_archive['tweet_id'] = dogsTwitter_archive['tweet_id'].astype('category')

#### Test

In [69]:
dogsTwitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2117 entries, 0 to 2355
Data columns (total 12 columns):
tweet_id              2117 non-null category
timestamp             2117 non-null object
source                2117 non-null object
text                  2117 non-null object
expanded_urls         2117 non-null object
rating_numerator      2117 non-null int64
rating_denominator    2117 non-null int64
name                  1399 non-null object
doggo                 2117 non-null object
floofer               2117 non-null object
pupper                2117 non-null object
puppo                 2117 non-null object
dtypes: category(1), int64(2), object(9)
memory usage: 379.1+ KB

In [70]:
dogsTwitter_archive.head()

,tweet_id,timestamp,source,text,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,2017-08-01 16:23:56 +0000,[Twitter for iPhone],This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,2017-08-01 00:17:27 +0000,[Twitter for iPhone],This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,2017-07-31 00:18:03 +0000,[Twitter for iPhone],This is Archie. He is a rare Norwegian Pouncin...,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,2017-07-30 15:58:51 +0000,[Twitter for iPhone],This is Darla. She commenced a snooze mid meal...,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,2017-07-29 16:00:24 +0000,[Twitter for iPhone],This is Franklin. He would like you to stop ca...,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None

### Cleaning for data 2 - twitter image predictions:

In [71]:
# making a copy before cleaning
dog_images_original = dog_images.copy()

#### Define

1.. Convert tweet_id column to category datatype

#### Code

In [72]:
# converting to categorical data
dog_images['tweet_id'] = dog_images['tweet_id'].astype('category')

#### Test

In [73]:
dog_images.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null category
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), category(1), float64(3), int64(1), object(4)
memory usage: 236.1+ KB

### Cleaning for data 3 - twitter API datadump:

In [74]:
# making a copy before cleaning
twitter_extractedDF_original = twitter_extractedDF.copy()

#### Define

1.. Convert to appropriate dtypes:   
        a. tweet_id column to category datatype  
        b. retweet_created_at to datetime format

#### Code

In [76]:
# converting to categorical data
twitter_extractedDF['tweet_id'] = twitter_extractedDF['tweet_id'].astype('category')

#### Test

In [77]:
twitter_extractedDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2347 entries, 0 to 2346
Data columns (total 4 columns):
tweet_id         2347 non-null category
retweet_count    2347 non-null int64
likes            2347 non-null int64
full_text        2347 non-null object
dtypes: category(1), int64(2), object(1)
memory usage: 158.0+ KB

### Tidiness issues:

### Cleaning for Data 1 - dogsTwitter_archive:

#### Define

1.. doggo, floofer, pupper, pupp columns should be merged into 1 column to represent the stage of dog.

#### Code

In [78]:
# Resetting dataframe index after all the dropping records and columns
dogsTwitter_archive.index = range(len(dogsTwitter_archive))

# Find all the unique values for various dog stage columns
print(dogsTwitter_archive.doggo.unique())
print(dogsTwitter_archive.floofer.unique())
print(dogsTwitter_archive.pupper.unique())
print(dogsTwitter_archive.puppo.unique())

# all values are either 'None' or god stage name. Hence, no unusal values

['None' 'doggo']
['None' 'floofer']
['None' 'pupper']
['None' 'puppo']

In [79]:
# Create a new column called 'dog_stage' and initialise it to nan 
dogsTwitter_archive['dog_stage'] = np.nan

# Find the dog stage
for index in range(len(dogsTwitter_archive)):
    if (dogsTwitter_archive['doggo'].iloc[index] == 'doggo'):
        dogsTwitter_archive['dog_stage'].iloc[index] = 'doggo'
    elif dogsTwitter_archive['floofer'].iloc[index] == 'floofer':
        dogsTwitter_archive['dog_stage'].iloc[index] = 'floofer'
    elif dogsTwitter_archive['pupper'].iloc[index] == 'pupper':
        dogsTwitter_archive['dog_stage'].iloc[index] = 'pupper'
    elif dogsTwitter_archive['puppo'].iloc[index] == 'puppo':
        dogsTwitter_archive['dog_stage'].iloc[index] = 'puppo'
    else:
        dogsTwitter_archive['dog_stage'].iloc[index] = np.NaN

#if multiple dogs and stages are present in tweet, only the first will be considered which I guess is reasonable to assume in current scenario
dogsTwitter_archive['dog_stage'].unique()

array([nan, 'doggo', 'puppo', 'pupper', 'floofer'], dtype=object)

In [80]:
dogsTwitter_archive['dog_stage'].value_counts()

pupper     222
doggo       84
puppo       23
floofer      9
Name: dog_stage, dtype: int64

In [81]:
# drop the individual dog stage columns
dogsTwitter_archive = dogsTwitter_archive.drop(['doggo','pupper','puppo','floofer'], axis = 1)

#### Test

In [82]:
dogsTwitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2117 entries, 0 to 2116
Data columns (total 9 columns):
tweet_id              2117 non-null category
timestamp             2117 non-null object
source                2117 non-null object
text                  2117 non-null object
expanded_urls         2117 non-null object
rating_numerator      2117 non-null int64
rating_denominator    2117 non-null int64
name                  1399 non-null object
dog_stage             338 non-null object
dtypes: category(1), int64(2), object(6)
memory usage: 233.1+ KB

### General - Merge all the 3 datasets

In [83]:
print(len(dogsTwitter_archive['tweet_id'].value_counts())); print(len(dogsTwitter_archive))
print(len(dog_images['tweet_id'].value_counts())); print(len(dog_images))
print(len(twitter_extractedDF['tweet_id'].value_counts())); print(len(twitter_extractedDF))

# No duplicated tweet_ids in the dataframes

2117
2117
2075
2075
2347
2347

In [84]:
len(twitter_extractedDF)

2347

In [85]:
# Performing an inner join to join all the dataframes
dogs_twitter_final = dogsTwitter_archive.merge(dog_images, on = 'tweet_id', how='inner')

dogs_twitter_final.head()
#dogs_twitter_final.info()

,tweet_id,timestamp,source,text,expanded_urls,rating_numerator,rating_denominator,name,dog_stage,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,892420643555336193,2017-08-01 16:23:56 +0000,[Twitter for iPhone],This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,NaN,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,1,orange,0.097049,False,bagel,0.085851,False,banana,0.076110,False
1,892177421306343426,2017-08-01 00:17:27 +0000,[Twitter for iPhone],This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,NaN,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,1,Chihuahua,0.323581,True,Pekinese,0.090647,True,papillon,0.068957,True
2,891815181378084864,2017-07-31 00:18:03 +0000,[Twitter for iPhone],This is Archie. He is a rare Norwegian Pouncin...,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,NaN,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,1,Chihuahua,0.716012,True,malamute,0.078253,True,kelpie,0.031379,True
3,891689557279858688,2017-07-30 15:58:51 +0000,[Twitter for iPhone],This is Darla. She commenced a snooze mid meal...,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,NaN,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,1,paper_towel,0.170278,False,Labrador_retriever,0.168086,True,spatula,0.040836,False
4,891327558926688256,2017-07-29 16:00:24 +0000,[Twitter for iPhone],This is Franklin. He would like you to stop ca...,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,NaN,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,2,basset,0.555712,True,English_springer,0.225770,True,German_short-haired_pointer,0.175219,True

In [86]:
dogs_twitter_final = dogs_twitter_final.merge(twitter_extractedDF, on = 'tweet_id', how='inner')

dogs_twitter_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1994 entries, 0 to 1993
Data columns (total 23 columns):
tweet_id              1994 non-null object
timestamp             1994 non-null object
source                1994 non-null object
text                  1994 non-null object
expanded_urls         1994 non-null object
rating_numerator      1994 non-null int64
rating_denominator    1994 non-null int64
name                  1357 non-null object
dog_stage             306 non-null object
jpg_url               1994 non-null object
img_num               1994 non-null int64
p1                    1994 non-null object
p1_conf               1994 non-null float64
p1_dog                1994 non-null bool
p2                    1994 non-null object
p2_conf               1994 non-null float64
p2_dog                1994 non-null bool
p3                    1994 non-null object
p3_conf               1994 non-null float64
p3_dog                1994 non-null bool
retweet_count         1994 non-null int64
likes                 1994 non-null int64
full_text             1994 non-null object
dtypes: bool(3), float64(3), int64(5), object(12)
memory usage: 333.0+ KB

### Writing into .csv file

In [89]:
# Writing the final data to csv file name - twitter_archive_master.csv
dogs_twitter_final.to_csv('twitter_archive_master.csv', index=False)

In [90]:
# Also write the individual cleaned datasets for reference, if required
dogsTwitter_archive.to_csv('dogsTwitter_archive_master.csv', index=False)
dog_images.to_csv('dog_images_master.csv', index=False)
twitter_extractedDF.to_csv('twitter_extractedDF_master.csv', index=False)

A lot more needs to be done to make this dataset completely clean. Some of the future work which I intent to do later is as listed below:

### Future Work

1. The image prediction file has dog breed prediction. Some of the tweet images has dogs + some other element (e.g., a shopping cart). The prediction file predicts the image as shopping cart with the highest confidence which is errorenous. This should be corrected in the file.   
Also, some images are not of dogs. Such records should also be removed from the dataset.  
2. Correct '&amp' in tweet 'text' column to just '&'.  
3. The tweet 'test' column can be further cleaned to remove all ratings and to have only text.  
4. The twitter API scrapped data dump file could be used to see if missing image files for tweets are available. If so, those records needn't be dropped just because they don't have images.  
5. Optimising the code for faster execution. Currently, only 'cleaning' the data has been concentrated on. Ideally, the code needs to be made faster too.